export interface Product {
  id: string
  name: string
  sku: string
  price?: number
  category: string
  brand: string
  image: string
  description: string
  specs: Record<string, string>
  hsn: string
  minOrderQty: number
  inStock: boolean
  isOffer?: boolean
  offerBadge?: string
  features?: string[]
  application?: string
  cta?: string
}

export const categories = [
  { id: "welding", name: "Welding Machines & Spot Welders", icon: "Zap", description: "Professional welding equipment" },
  { id: "spray-guns", name: "Paint & Spray Systems", icon: "Paintbrush", description: "Professional spray guns & booths" },
  { id: "lifting", name: "Vehicle Lifts & Hoists", icon: "ArrowUpCircle", description: "Two-post lifts, engine cranes" },
  { id: "transmission", name: "Transmission Jacks & Engine Cranes", icon: "Settings2", description: "Automotive service equipment" },
  { id: "special-tools", name: "Collision & Special Tools", icon: "Wrench", description: "Dent pullers, hydraulic presses" },
  { id: "pneumatic", name: "Air Compressors & Pneumatic", icon: "Wind", description: "Industrial air systems" },
  { id: "painting", name: "Paint Curing & Infrared Systems", icon: "Sun", description: "Infrared booths & curing lamps" },
  { id: "measurement", name: "Precision Measurement", icon: "Ruler", description: "Professional testing & measurement" },
  { id: "power-tools", name: "Professional Power Tools", icon: "Hammer", description: "Bosch & DeWALT professional grade" },
  { id: "finishing", name: "Finishing & Polishing", icon: "Sparkles", description: "Professional sanding & polishing" },
]

export const brands = [
  "LINICH",
  "Blue Point",
  "CAR-O-LINER",
  "SATA",
  "DeVilbiss",
  "3M",
  "Bosch",
  "DeWALT",
  "Fluke",
  "Mitutoyo",
  "Mirka",
  "Menzerna",
  "PCL",
  "ACCURA",
]

export const products: Product[] = [
  // ==================== COLLISION REPAIR ====================
  {
    id: "1",
    name: "LINICH 3100 Auto Puller",
    sku: "LIN-3100",
    category: "special-tools",
    brand: "LINICH",
    image: "/images/products/1-linich-auto-puller.jpg",
    description: "Professional automatic dent pulling machine with dual triggering modes for precision body panel repair.",
    specs: {
      "Input Voltage": "220-230V AC",
      "Max Welding Current": "3000A",
      "Max Output": "11 KVA",
      "Protection Rating": "IP 21",
      Weight: "29 kg",
    },
    features: ["Dual manual & automatic modes", "German thyristor technology", "Max 3000A current", "Complete kit"],
    application: "Collision repair workshops, body shop operations",
    cta: "Request Quote",
    hsn: "8508",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "2",
    name: "Blue-Point Multifunction Dent Pulling Machine",
    sku: "BP-MDPM",
    category: "special-tools",
    brand: "Blue Point",
    image: "/images/products/bp-dent-01-blue-point-dent-machine.jpg",
    description: "Professional dent puller with minimal metal distortion for thin car body panels.",
    specs: {
      "Input Voltage": "220V / 380V",
      "Max Welding Current": "1800 A",
      "Welding Time": "0-99 seconds",
      "Rated Power": "11.5 KVA",
    },
    features: ["Time-controlled welding", "Thin panel capability", "Professional accessories", "Long warranty"],
    application: "Authorized service centers, collision repair centers",
    cta: "Request Quote",
    hsn: "8515",
    minOrderQty: 1,
    inStock: true,
  },

  // ==================== SPOT WELDERS ====================
  {
    id: "3",
    name: "LINICH SPOT LCR-70 Dual-Purpose Welder",
    sku: "LIN-LCR70",
    category: "welding",
    brand: "LINICH",
    image: "/images/products/linich-lcr70-advanced-welder.jpg",
    description: "Heavy-duty spot welder and dent puller with temperature-controlled air-cooled system.",
    specs: {
      "Input Voltage": "400V AC, 50Hz",
      "Max Output Current": "13,500 A",
      "Output KVA": "47.3 KVA @ 50%",
      "Weight": "146 kg",
      "Cooling": "Temperature-controlled air-cooled",
    },
    features: ["Spot welding & dent pulling", "Dual mode operation", "Heavy-duty design", "Industrial grade"],
    application: "Professional collision repair, body shop operations",
    cta: "Request Quote",
    hsn: "8515",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "4",
    name: "CAR-O-LINER CTR-9 Inverter Spot Welder",
    sku: "CAR-CTR9",
    category: "welding",
    brand: "CAR-O-LINER",
    image: "/images/products/car-o-ctr9-car-o-liner-spot-welder.jpg",
    description: "Lightweight inverter spot welder with ergonomic design and CANBUS precision control.",
    specs: {
      Technology: "Inverter-based",
      "Ergonomic Design": "Lightweight swivel handle",
      Communication: "CANBUS precision control",
      "Energy Efficient": "Yes",
    },
    features: ["Lightweight & ergonomic", "Fast welding cycles", "Precision control", "Compact design"],
    application: "Collision repair centers, body shop environments",
    cta: "Request Quote",
    hsn: "8515",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "5",
    name: "CAR-O-LINER CRX Inverter Spot Welder",
    sku: "CAR-CRX",
    category: "welding",
    brand: "CAR-O-LINER",
    image: "/images/products/car-o-crx-car-o-liner-spot-welder.jpg",
    description: "Compact inverter-based spot welder with superior mobility for collision repair operations.",
    specs: {
      Technology: "Inverter-based",
      Design: "Compact & lightweight",
      Mobility: "High portability",
      Operation: "Easy & intuitive",
    },
    features: ["Compact design", "Lightweight construction", "Excellent mobility", "Stable welding"],
    application: "Professional collision repair, advanced body shops",
    cta: "Request Quote",
    hsn: "8515",
    minOrderQty: 1,
    inStock: true,
  },

  // ==================== MIG WELDERS ====================
  {
    id: "6",
    name: "Blue-Point Inverter MIG Welder 160A",
    sku: "BP-MIG160",
    category: "welding",
    brand: "Blue Point",
    image: "/images/products/bp-mig-160-blue-point-mig-welder.jpg",
    description: "Professional dual-function MIG & MMA welding machine with IGBT inverter technology.",
    specs: {
      "Input Voltage": "230V ±15%",
      "Output Current": "Up to 160A",
      "Wire Diameter": "0.8 – 1.2 mm",
      "Duty Cycle": "40%",
      Technology: "IGBT Inverter",
    },
    features: ["MIG & MMA compatible", "IGBT inverter technology", "High efficiency", "Professional grade"],
    application: "Automotive fabrication, workshop welding",
    cta: "Request Quote",
    hsn: "8515",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "7",
    name: "AUTOMIG MW-250 Industrial MIG Welder",
    sku: "AUTO-250",
    category: "welding",
    brand: "LINICH",
    image: "/images/products/automig-mw-250-industrial-mig-welder.jpg",
    description: "Three-phase MIG/MAG welding machine with optimized inductor for spatter-free welding.",
    specs: {
      "Power Supply": "3-Phase, 440V",
      "Output Current": "60–250A",
      "Wire Diameter": "0.8 – 1.2 mm",
      "Weight": "70 kg",
      "KVA": "High performance",
    },
    features: ["3-phase power", "Spatter reduction", "Industrial grade", "High output"],
    application: "Industrial workshops, high-volume fabrication",
    cta: "Request Quote",
    hsn: "8515",
    minOrderQty: 1,
    inStock: true,
  },

  // ==================== VEHICLE LIFTS ====================
  {
    id: "8",
    name: "4-Ton Hydraulic Two-Post Lift",
    sku: "HTL-4T",
    category: "lifting",
    brand: "LINICH",
    image: "/images/products/3-hydraulic-two-post-lift.jpg",
    description: "Professional 4-ton capacity hydraulic lift with symmetric/asymmetric arms and wide door opening.",
    specs: {
      "Lifting Capacity": "4000 kgs",
      "Max Height": "1900 mm",
      "Machine Height": "3600 mm",
      "Motor": "2.2 Kw",
      "Power": "380V / 3 Phase",
    },
    features: ["4-ton capacity", "Symmetric & asymmetric arms", "Wide opening", "Professional design"],
    application: "Professional workshops, service centers",
    cta: "Request Quote",
    hsn: "84281000",
    minOrderQty: 1,
    inStock: true,
  },

  // ==================== TRANSMISSION & ENGINE EQUIPMENT ====================
  {
    id: "9",
    name: "Transmission Jack 1 Ton",
    sku: "TJ-1T",
    category: "transmission",
    brand: "LINICH",
    image: "/images/products/7-transmission-jack-1ton.jpg",
    description: "Hydraulic transmission jack with 1-ton capacity for safe controlled transmission service.",
    specs: {
      Capacity: "1 Ton",
      "Min Height": "860mm",
      "Max Height": "1835mm",
      Weight: "90 kg",
    },
    features: ["1-ton capacity", "Adjustable height", "Safety valve", "Smooth operation"],
    application: "Transmission service, vehicle maintenance",
    cta: "Request Quote",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "10",
    name: "Transmission Jack 2 Ton",
    sku: "TJ-2T",
    category: "transmission",
    brand: "LINICH",
    image: "/images/products/8-transmission-jack-2ton.jpg",
    description: "Heavy-duty 2-ton hydraulic transmission jack with stabilizing base for larger vehicles.",
    specs: {
      Capacity: "2 Ton",
      "Min Height": "1580mm",
      "Max Width": "1040mm",
      Weight: "74 kg",
    },
    features: ["2-ton capacity", "Stabilizing base", "Professional hydraulics", "Heavy-duty construction"],
    application: "Mid-size & large vehicle service, fleet maintenance",
    cta: "Request Quote",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "11",
    name: "Engine Crane 0.5 Ton",
    sku: "EC-500",
    category: "transmission",
    brand: "LINICH",
    image: "/images/products/9-engine-crane-500kg.jpg",
    description: "Compact folding engine crane for light-duty engine lifting and service operations.",
    specs: {
      Capacity: "0.5-0.6 Ton",
      "Min Height": "1200mm",
      "Max Height": "1795mm",
      Weight: "41 kg",
    },
    features: ["0.5-ton capacity", "Folding design", "Portable", "Easy to store"],
    application: "Small workshops, quick engine service",
    cta: "Request Quote",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "12",
    name: "Engine Crane 2 Ton",
    sku: "EC-2T",
    category: "transmission",
    brand: "LINICH",
    image: "/images/products/engine-crane-2ton.jpg",
    description: "Professional 2-ton engine crane with smooth hydraulic control for engine overhaul operations.",
    specs: {
      "Lifting Capacity": "2 Ton",
      "Frame": "Reinforced steel",
      "Control": "Hydraulic",
      "Wheels": "Heavy-duty casters",
    },
    features: ["2-ton capacity", "Smooth operation", "Mobile design", "Professional grade"],
    application: "Engine service, overhaul operations",
    cta: "Request Quote",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // ==================== HYDRAULIC PRESSES ====================
  {
    id: "13",
    name: "Hydraulic Press 20 Ton",
    sku: "HP-20T",
    category: "special-tools",
    brand: "LINICH",
    image: "/images/products/10-hydraulic-press-20ton.jpg",
    description: "Precision 20-ton hydraulic press for bearing extraction and component pressing.",
    specs: {
      Capacity: "20 Ton",
      "Working Range": "0-955mm",
      Stroke: "154mm",
      "Bed Width": "550mm",
    },
    features: ["20-ton capacity", "Precision design", "Wide working range", "Industrial grade"],
    application: "Bearing removal, component pressing, mechanical work",
    cta: "Request Quote",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "14",
    name: "Hydraulic Press 30 Ton",
    sku: "HP-30T",
    category: "special-tools",
    brand: "LINICH",
    image: "/images/products/11-hydraulic-press-30ton.jpg",
    description: "Heavy-duty 30-ton hydraulic press for demanding metal pressing and fabrication work.",
    specs: {
      Capacity: "30 Ton",
      "Working Range": "0-1050mm",
      Stroke: "162mm",
      "Bed Width": "460mm",
    },
    features: ["30-ton capacity", "Heavy-duty design", "Extended range", "Professional engineering"],
    application: "Heavy metal pressing, bearing operations, component work",
    cta: "Request Quote",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "15",
    name: "Hydraulic Press 50 Ton",
    sku: "HP-50T",
    category: "special-tools",
    brand: "LINICH",
    image: "/images/products/hydraulic-press-50ton-industrial.jpg",
    description: "Industrial-grade 50-ton hydraulic press for high-force metal operations.",
    specs: {
      Capacity: "50 Ton",
      "Pressure Output": "Maximum",
      "Working Range": "Fully adjustable",
      "Structure": "Robust welded steel",
    },
    features: ["50-ton capacity", "Maximum pressure output", "Industrial design", "Heavy-duty frame"],
    application: "High-force metal pressing, complex fabrication",
    cta: "Request Quote",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // ==================== PNEUMATIC & AIR SYSTEMS ====================
  {
    id: "16",
    name: "Air Compressor 80L Tank",
    sku: "AC-80L",
    category: "pneumatic",
    brand: "LINICH",
    image: "/images/products/6-air-compressor-80l.jpg",
    description: "Heavy-duty 80-liter industrial air compressor with dry/wet functionality.",
    specs: {
      Capacity: "80 Liters",
      Power: "3000W",
      "Air Flow": "106 L/min",
      Function: "Dry/Wet",
    },
    features: ["80L capacity", "3000W motor", "Dual functionality", "High air flow"],
    application: "Workshop pneumatic operations, paint booth use",
    cta: "Request Quote",
    hsn: "8414",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "17",
    name: "PCL-SUMO Nitrogen Generator",
    sku: "PCL-SUMO",
    category: "pneumatic",
    brand: "PCL",
    image: "/images/products/pcl-sumo-nitrogen.jpg",
    description: "Professional PSA nitrogen generation system with simultaneous 4-tire inflation capability.",
    specs: {
      Technology: "PSA Nitrogen Generation",
      Capacity: "4 tires simultaneous",
      "Preset Function": "Yes",
      Purity: "High N₂ levels",
    },
    features: ["PSA technology", "4-tire inflation", "High purity N2", "Mobile design"],
    application: "Tire inflation, fleet maintenance",
    cta: "Request Quote",
    hsn: "8414",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "18",
    name: "ACCURA D60 Digital Inflator",
    sku: "ACCURA-D60",
    category: "pneumatic",
    brand: "ACCURA",
    image: "/images/products/accura-d60-inflator-precision.jpg",
    description: "Compact digital inflator with high-accuracy pressure display for precise tire inflation.",
    specs: {
      Display: "Digital pressure accuracy",
      Design: "Compact & durable",
      Features: "Professional grade",
      Range: "Full vehicle range",
    },
    features: ["Digital display", "High accuracy", "Compact design", "Professional grade"],
    application: "Tire inflation, pressure diagnostics",
    cta: "Request Quote",
    hsn: "8414",
    minOrderQty: 1,
    inStock: true,
  },

  // ==================== PAINTING & SPRAY SYSTEMS ====================
  {
    id: "19",
    name: "Infrared Paint Booth 3000W",
    sku: "IPB-3000",
    category: "painting",
    brand: "LINICH",
    image: "/images/products/13-infrared-paint-booth.jpg",
    description: "Professional infrared curing booth with adjustable temperature and auto distance sensing.",
    specs: {
      Power: "3000W",
      "Height Adjust": "0.2-2.1m",
      "Temperature": "40-80°C",
      "Timer": "0.1-30 min",
    },
    features: ["3000W power", "Auto sensor", "Temperature control", "Electronic timer"],
    application: "Paint booths, paint curing operations",
    cta: "Request Quote",
    hsn: "8516",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "20",
    name: "SATAjet 1000 IC Paint Spray Gun",
    sku: "SATA-1000IC",
    category: "spray-guns",
    brand: "SATA",
    image: "/images/products/sata-jet1000-sata-paint-spray-gun.jpg",
    description: "Premium German-engineered HVLP spray gun for superior atomization and finish quality.",
    specs: {
      "Air Distribution": "Precision system",
      "Transfer Efficiency": "High",
      "Nozzle Design": "Optimized",
      "Finish Quality": "Professional",
    },
    features: ["HVLP technology", "Superior atomization", "German engineering", "High efficiency"],
    application: "Automotive refinishing, high-end paint work",
    cta: "Request Quote",
    hsn: "7311",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "21",
    name: "3M Performance Spray Gun",
    sku: "3M-SG",
    category: "spray-guns",
    brand: "3M",
    image: "/images/products/20-3m-performance-spray-gun.jpg",
    description: "Professional automotive spray gun with precision fluid delivery and adjustable pattern.",
    specs: {
      Type: "HVLP compatible",
      "Fluid Capacity": "Standard cup",
      "Spray Pattern": "Adjustable",
      "Nozzle": "Precision design",
    },
    features: ["HVLP compatible", "Precision nozzle", "Adjustable pattern", "Professional finish"],
    application: "Automotive painting, professional refinishing",
    cta: "Request Quote",
    hsn: "7311",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "22",
    name: "DeVilbiss DV1 Basecoat Spray Gun",
    sku: "DVB-DV1",
    category: "spray-guns",
    brand: "DeVilbiss",
    image: "/images/products/devilbiss-dv1-basecoat-spray-gun.jpg",
    description: "Professional basecoat spray gun with exceptional atomization for modern automotive coatings.",
    specs: {
      Body: "Lightweight balanced",
      "Material Transfer": "High efficiency",
      Overspray: "Minimal waste",
      Performance: "Consistent application",
    },
    features: ["Lightweight design", "High transfer efficiency", "Minimal overspray", "Professional grade"],
    application: "Professional refinishing, basecoat application",
    cta: "Request Quote",
    hsn: "7311",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "23",
    name: "DeVilbiss ProLite Spray Gun",
    sku: "DVB-PROLITE",
    category: "spray-guns",
    brand: "DeVilbiss",
    image: "/images/products/devilbiss-prolite-spray-gun.jpg",
    description: "Professional spray gun with forged aluminum body for maximum atomization and durability.",
    specs: {
      Body: "Forged aluminum",
      "Fluid Nozzle": "Stainless steel",
      "Spray Pattern": "Excellent consistency",
      "Service Life": "Extended duration",
    },
    features: ["Forged aluminum", "Stainless nozzle", "Excellent spray", "Long service life"],
    application: "Demanding automotive paint environments",
    cta: "Request Quote",
    hsn: "7311",
    minOrderQty: 1,
    inStock: true,
  },

  // ==================== WORKSHOP VACUUM & CLEANING ====================
  {
    id: "24",
    name: "Vacuum Cleaner 80L Industrial",
    sku: "VC-80L",
    category: "pneumatic",
    brand: "LINICH",
    image: "/images/products/vacuum-cleaner-80l.jpg",
    description: "Industrial 80-liter dry and wet vacuum cleaner for workshop dust and debris removal.",
    specs: {
      Capacity: "80L",
      Functionality: "Dry & wet",
      "Suction Power": "High",
      "Cooling System": "Recyclable",
    },
    features: ["80L capacity", "Dry & wet capable", "High suction", "Durable construction"],
    application: "Workshop cleaning, paint booth cleaning",
    cta: "Request Quote",
    hsn: "8408",
    minOrderQty: 1,
    inStock: true,
  },

  // ==================== MEASUREMENT & DIAGNOSTICS ====================
  {
    id: "25",
    name: "Fluke Digital Multimeter",
    sku: "FM-175",
    category: "measurement",
    brand: "Fluke",
    image: "/images/products/16-fluke-digital-multimeter.jpg",
    description: "Professional digital multimeter for electrical system diagnostics and testing.",
    specs: {
      Display: "Digital LCD",
      Functions: "Voltage, Current, Resistance, Temperature",
      Accuracy: "High precision",
      Rating: "CAT III",
    },
    features: ["Auto-ranging", "Backlit display", "Multiple functions", "Professional accuracy"],
    application: "Electrical diagnostics, vehicle testing",
    cta: "Request Quote",
    hsn: "9030",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "26",
    name: "Mitutoyo Micrometer 25mm",
    sku: "MM-25",
    category: "measurement",
    brand: "Mitutoyo",
    image: "/images/products/17-mitutoyo-micrometer.jpg",
    description: "Precision micrometer for accurate measurements up to 25mm with ±0.01mm accuracy.",
    specs: {
      Range: "0-25mm",
      Accuracy: "±0.01mm",
      Material: "Chrome plated steel",
      Construction: "Professional grade",
    },
    features: ["0.01mm accuracy", "Chrome plated", "Easy reading", "Professional precision"],
    application: "Engine work, bore measurement, precision inspection",
    cta: "Request Quote",
    hsn: "9031",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "27",
    name: "Bearing Puller Set",
    sku: "BP-SET",
    category: "special-tools",
    brand: "Blue Point",
    image: "/images/products/15-bearing-puller-set.jpg",
    description: "Professional 6-piece bearing puller set with range 75mm-300mm for precise extraction.",
    specs: {
      "Sizes Included": "75mm to 300mm",
      Material: "Hardened steel",
      Pieces: "6",
      "Design": "Precision engineered",
    },
    features: ["6-piece set", "Wide range", "Hardened steel", "Precise design"],
    application: "Bearing removal, shaft extraction, mechanical work",
    cta: "Request Quote",
    hsn: "8205",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "28",
    name: "Digital Torque Wrench",
    sku: "DTW-PRO",
    category: "measurement",
    brand: "Blue Point",
    image: "/images/products/27-digital-torque-wrench.jpg",
    description: "Digital precision torque wrench with memory and data lock for accurate fastening.",
    specs: {
      Range: "0-300 Nm",
      Accuracy: "±3%",
      Display: "Digital LCD",
      Features: "Memory & overload protection",
    },
    features: ["Digital display", "Memory function", "High accuracy", "Overload protection"],
    application: "Critical fastening, engine assembly",
    cta: "Request Quote",
    hsn: "8205",
    minOrderQty: 1,
    inStock: true,
  },

  // ==================== PROFESSIONAL POWER TOOLS ====================
  {
    id: "29",
    name: "Bosch GWS 800 Angle Grinder",
    sku: "BOSCH-GWS800",
    category: "power-tools",
    brand: "Bosch",
    image: "/images/products/29-bosch-gws-800-angle-grinder.jpg",
    description: "Professional 800W angle grinder with 100mm disc and 11,000 RPM for cutting and grinding.",
    specs: {
      Power: "800W",
      "Disc Size": "100mm",
      RPM: "11,000",
      Weight: "1.8kg",
    },
    features: ["800W motor", "11,000 RPM", "Professional build", "Safety guard"],
    application: "Metal cutting, grinding operations",
    cta: "Request Quote",
    hsn: "84672100",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "30",
    name: "DeWALT Angle Grinder 800W",
    sku: "DW-AG800",
    category: "power-tools",
    brand: "DeWALT",
    image: "/images/products/19-dewalt-angle-grinder.jpg",
    description: "Professional 800W angle grinder with variable speed and ergonomic grip design.",
    specs: {
      Power: "800W",
      "Disc Size": "100mm",
      "No-load Speed": "11,000 rpm",
      "Grip": "Ergonomic",
    },
    features: ["Variable speed", "Ergonomic design", "Professional grade", "Reliable performance"],
    application: "Metal cutting, surface finishing",
    cta: "Request Quote",
    hsn: "8463",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "31",
    name: "Bosch GPO 12 CE Polisher",
    sku: "BOSCH-GPO12",
    category: "finishing",
    brand: "Bosch",
    image: "/images/products/bosch-gpo12-polisher.jpg",
    description: "Professional polishing machine with variable speed control and high-torque motor.",
    specs: {
      Power: "1200W",
      "Variable Speed": "Yes",
      "Torque Motor": "High",
      Applications: "Professional polishing",
    },
    features: ["Variable speed", "High torque", "Professional motor", "Superior finish"],
    application: "Surface finishing, professional detailing",
    cta: "Request Quote",
    hsn: "8463",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "32",
    name: "Mirka Orbital Sander",
    sku: "MIRKA-SAND",
    category: "power-tools",
    brand: "Mirka",
    image: "/images/products/54-mirka-orbital-sander.jpg",
    description: "Professional dust-free orbital sander with 150mm pad for automotive refinishing.",
    specs: {
      "Sanding Plate": "150mm",
      Power: "1250W",
      "Speed": "750-3000 rpm",
      "Dust Collection": "Advanced",
    },
    features: ["Dust-free technology", "Variable speed", "150mm pad", "Professional grade"],
    application: "Surface preparation, automotive refinishing",
    cta: "Request Quote",
    hsn: "8463",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "33",
    name: "Mirka Sanding & Polishing Systems",
    sku: "MIRKA-SYSTEM",
    category: "finishing",
    brand: "Mirka",
    image: "/images/products/mirka-systems-advanced.jpg",
    description: "Professional dust-free sanding system with ergonomic power tools for refinishing.",
    specs: {
      "Dust-free": "Yes",
      Ergonomic: "Yes",
      "Industry Approved": "Yes",
      "Technology": "Advanced",
    },
    features: ["Dust-free technology", "Ergonomic design", "Industry approved", "Professional system"],
    application: "Professional automotive refinishing",
    cta: "Request Quote",
    hsn: "8463",
    minOrderQty: 1,
    inStock: true,
  },

  // ==================== FINISHING & DETAILING ====================
  {
    id: "34",
    name: "Menzerna Polishing Compounds Set",
    sku: "MENZERNA-POLISH",
    category: "finishing",
    brand: "Menzerna",
    image: "/images/products/menzerna-compounds-ultimate.jpg",
    description: "Professional polishing compounds for high-gloss finish with cutting and polishing stages.",
    specs: {
      "High-gloss": "Yes",
      "Cutting Stages": "Multiple",
      "Polishing Stages": "Multiple",
      "Application": "Professional detailing",
    },
    features: ["Multiple stages", "High-gloss finish", "Professional quality", "Long-lasting"],
    application: "Professional vehicle detailing",
    cta: "Request Quote",
    hsn: "3405",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "35",
    name: "MaxShine Cordless Polisher",
    sku: "MAX-POLISH",
    category: "power-tools",
    brand: "Mirka",
    image: "/images/products/38-maxshine-polisher.jpg",
    description: "Cordless orbital polisher with variable speed and LED work light for professional detailing.",
    specs: {
      Speed: "600-3000 RPM",
      "Pad Size": "5 inch",
      Battery: "36V Lithium",
      "Runtime": "2 hours",
    },
    features: ["Cordless design", "Variable speed", "LED light", "Professional grade"],
    application: "Paint protection, professional detailing",
    cta: "Request Quote",
    hsn: "8509",
    minOrderQty: 1,
    inStock: true,
  },

  // ==================== SPECIAL WORKSHOP EQUIPMENT ====================
  {
    id: "36",
    name: "Spring Compressor Hydraulic",
    sku: "HCSC-PRO",
    category: "special-tools",
    brand: "LINICH",
    image: "/images/products/spring-compressor.jpg",
    description: "Hydraulic coil spring compressor for safe suspension spring compression and removal.",
    specs: {
      "Spring Type": "Coil",
      "Max Opening": "300mm",
      Material: "Forged steel",
      "Safety": "Lock pins included",
    },
    features: ["Hydraulic operation", "Adjustable opening", "Heavy-duty steel", "Safety locks"],
    application: "Suspension service, spring replacement",
    cta: "Request Quote",
    hsn: "82079010",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "37",
    name: "Engine Stand Professional",
    sku: "ES-PRO",
    category: "special-tools",
    brand: "LINICH",
    image: "/images/products/engine-stand-professional-heavy-duty.jpg",
    description: "Heavy-duty engine stand for safe 360° rotation during engine rebuilding operations.",
    specs: {
      Mounting: "Safe & secure",
      Rotation: "360° capability",
      "Weight Capacity": "High",
      Applications: "Engine rebuilding",
    },
    features: ["360° rotation", "Heavy-duty frame", "Secure mounting", "Professional grade"],
    application: "Engine overhaul, rebuilding work",
    cta: "Request Quote",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "38",
    name: "5-Ton Floor Jack",
    sku: "FJ-5T",
    category: "lifting",
    brand: "LINICH",
    image: "/images/products/14-5-ton-floor-jack.jpg",
    description: "Professional 5-ton hydraulic floor jack with quick-release and swivel casters.",
    specs: {
      Capacity: "5 Tons",
      "Lifting Height": "Standard range",
      Wheels: "Swivel casters",
      "Relief Valve": "Yes",
    },
    features: ["5-ton capacity", "Quick-release", "Dual pump", "Maneuverable"],
    application: "Routine vehicle maintenance, tire service",
    cta: "Request Quote",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "39",
    name: "Axle Stand 3 Ton (Pair)",
    sku: "AS-3T",
    category: "lifting",
    brand: "LINICH",
    image: "/images/products/axle-stand-3ton-certified.jpg",
    description: "Certified 3-ton axle stands for secure vehicle support during maintenance work.",
    specs: {
      Capacity: "3 Ton each",
      "Height Adjustment": "Locking mechanism",
      "Base Design": "Ultra-stable",
      Certification: "Professional rated",
    },
    features: ["3-ton capacity", "Height adjustable", "Stable base", "Safety certified"],
    application: "Vehicle support, maintenance operations",
    cta: "Request Quote",
    hsn: "8425",
    minOrderQty: 2,
    inStock: true,
  },
  {
    id: "40",
    name: "10-Ton Body Puller Kit",
    sku: "BPK-10T",
    category: "special-tools",
    brand: "Blue Point",
    image: "/images/products/body-puller-kit-10ton-professional.jpg",
    description: "Complete 10-ton body puller kit for dent removal and structural frame repair.",
    specs: {
      Capacity: "10 Ton",
      "Kit Contents": "Complete professional set",
      "Applications": "Dent & frame repair",
      "Storage": "Metal box",
    },
    features: ["10-ton capacity", "Complete set", "Professional grade", "Easy transport"],
    application: "Collision repair, body work",
    cta: "Request Quote",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "41",
    name: "Wheel Dolly Set",
    sku: "WD-SET",
    category: "lifting",
    brand: "LINICH",
    image: "/images/products/wheel-dolly-heavy-duty-steel.jpg",
    description: "Heavy-duty steel wheel dollies for easy vehicle maneuvering in workshops.",
    specs: {
      "Material": "Heavy-duty steel",
      Wheels: "Smooth rolling casters",
      Positioning: "Easy movement",
      "Features": "Professional grade",
    },
    features: ["Steel construction", "Smooth casters", "Professional design", "High capacity"],
    application: "Vehicle positioning, workshop movement",
    cta: "Request Quote",
    hsn: "8708",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "42",
    name: "Engine Support Beam",
    sku: "ESB-PRO",
    category: "lifting",
    brand: "LINICH",
    image: "/images/products/engine-support-beam-heavy-duty.jpg",
    description: "Heavy-duty engine support beam for secure engine support during transmission removal.",
    specs: {
      "Support Arms": "Adjustable & reinforced",
      Construction: "Heavy-duty steel",
      "Mounting": "Secure system",
      "Applications": "Engine support service",
    },
    features: ["Adjustable arms", "Heavy-duty frame", "Secure mounting", "Professional grade"],
    application: "Transmission service, engine support",
    cta: "Request Quote",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "43",
    name: "Car Creeper Professional",
    sku: "CC-PRO",
    category: "special-tools",
    brand: "LINICH",
    image: "/images/products/car-creeper-professional-deluxe.jpg",
    description: "Professional low-profile car creeper with padded surface for under-vehicle comfort.",
    specs: {
      Design: "Low-profile ergonomic",
      "Casters": "Smooth rolling",
      Padding: "High-density",
      "Features": "Professional grade",
    },
    features: ["Ergonomic design", "Padded comfort", "Smooth movement", "Professional build"],
    application: "Under-vehicle inspections, repair access",
    cta: "Request Quote",
    hsn: "94019090",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "44",
    name: "Tool Storage Chest Heavy Duty",
    sku: "TSC-HD",
    category: "special-tools",
    brand: "LINICH",
    image: "/images/products/41-tool-storage-chest.jpg",
    description: "Professional-grade 7-drawer tool chest with secure key locking system.",
    specs: {
      Material: "Steel",
      Drawers: "7",
      "Locking": "Key lock system",
      Capacity: "500kg load",
    },
    features: ["7 drawers", "Steel construction", "Key lock", "Heavy-duty"],
    application: "Workshop tool storage, organization",
    cta: "Request Quote",
    hsn: "7326",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "45",
    name: "Pneumatic Impact Wrench 1/2\"",
    sku: "PIW-12",
    category: "pneumatic",
    brand: "Blue Point",
    image: "/images/products/37-pneumatic-impact-wrench.jpg",
    description: "Heavy-duty 1/2\" pneumatic impact wrench for tire service and fastener removal.",
    specs: {
      Drive: '1/2"',
      Torque: "680 Nm",
      RPM: "7000",
      "Air Consumption": "6.2 CFM",
    },
    features: ["680 Nm torque", "7000 RPM", "Professional grade", "Air powered"],
    application: "Tire service, bolt removal",
    cta: "Request Quote",
    hsn: "84672910",
    minOrderQty: 1,
    inStock: true,
  },
  // ==================== COLLISION / FRAME EQUIPMENT ====================
  {
    id: "46",
    name: "10-Ton Body Frame Straightener",
    sku: "BFS-10T",
    category: "special-tools",
    brand: "LINICH",
    image: "/images/products/body-frame-straightener-10ton.jpg",
    description: "Heavy-duty 10-ton body frame straightener designed for chassis alignment and structural repair work.",
    specs: {
      Capacity: "10 Ton",
      Operation: "Hydraulic",
      Construction: "Reinforced steel",
      Usage: "Structural frame repair",
    },
    features: ["10-ton pulling force", "Rigid steel frame", "Workshop-grade hydraulics", "Professional collision repair"],
    application: "Collision repair centers, frame straightening operations",
    cta: "Request Quote",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "47",
    name: "Sliding Hammer Dent Pulling Kit",
    sku: "SH-DENT",
    category: "special-tools",
    brand: "LINICH",
    image: "/images/products/sliding-hammer-dent-puller.jpg",
    description: "Professional sliding hammer kit for controlled dent pulling and panel correction.",
    specs: {
      Material: "Hardened steel",
      Operation: "Manual impact",
      Accessories: "Multiple hooks & adapters",
      Finish: "Anti-corrosion coating",
    },
    features: ["Controlled impact", "Multiple adapters", "Durable steel", "Easy handling"],
    application: "Body panel repair, dent pulling",
    cta: "Request Quote",
    hsn: "8205",
    minOrderQty: 1,
    inStock: true,
  },

  // ==================== LIFTING & WORKSHOP UTILITIES ====================
  {
    id: "48",
    name: "Chain Lever Block 1.5 Ton",
    sku: "CLB-1.5T",
    category: "lifting",
    brand: "LINICH",
    image: "/images/products/chain-lever-block-1.5ton.jpg",
    description: "Compact 1.5-ton chain lever block for lifting and positioning heavy components.",
    specs: {
      Capacity: "1.5 Ton",
      Chain: "Hardened load chain",
      Operation: "Manual lever",
      Safety: "Overload protection",
    },
    features: ["Compact size", "High safety factor", "Smooth lifting", "Workshop grade"],
    application: "Engine handling, workshop lifting",
    cta: "Request Quote",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "49",
    name: "Chain Lever Block 3 Ton",
    sku: "CLB-3T",
    category: "lifting",
    brand: "LINICH",
    image: "/images/products/chain-lever-block-3ton.jpg",
    description: "Heavy-duty 3-ton chain lever block for industrial lifting applications.",
    specs: {
      Capacity: "3 Ton",
      Chain: "High-strength alloy",
      Operation: "Manual",
      Safety: "Mechanical brake",
    },
    features: ["3-ton capacity", "Robust construction", "Safe operation", "Industrial rated"],
    application: "Heavy component lifting, workshop operations",
    cta: "Request Quote",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // ==================== PAINT & AIR ACCESSORIES ====================
  {
    id: "50",
    name: "FLG Cricket Spray Gun",
    sku: "FLG-CRICKET",
    category: "spray-guns",
    brand: "DeVilbiss",
    image: "/images/products/flg-cricket-spray-gun.jpg",
    description: "Entry-level professional spray gun designed for consistent paint application.",
    specs: {
      Type: "HVLP",
      Cup: "Gravity feed",
      Body: "Lightweight aluminum",
      Finish: "Professional spray pattern",
    },
    features: ["Consistent atomization", "Lightweight body", "Easy cleaning", "Professional finish"],
    application: "Automotive refinishing, paint workshops",
    cta: "Request Quote",
    hsn: "7311",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "51",
    name: "Pro Air-2 Breathing System",
    sku: "PROAIR-2",
    category: "spray-guns",
    brand: "DeVilbiss",
    image: "/images/products/pro-air-2-breathing-system.jpg",
    description: "Professional air-fed breathing system for paint booth safety and clean airflow.",
    specs: {
      AirQuality: "Filtered breathable air",
      Application: "Paint booth use",
      Safety: "Certified breathing system",
      Design: "Workshop compliant",
    },
    features: ["Clean breathable air", "Paint booth safety", "Certified system", "Professional use"],
    application: "Paint booths, professional refinishing environments",
    cta: "Request Quote",
    hsn: "9020",
    minOrderQty: 1,
    inStock: true,
  },

  // ==================== MEASUREMENT & SERVICE TOOLS ====================
  {
    id: "52",
    name: "Digital Tyre Inflator",
    sku: "DTI-PRO",
    category: "measurement",
    brand: "ACCURA",
    image: "/images/products/digital-tyre-inflator.jpg",
    description: "Digital tyre inflator with accurate pressure measurement for workshop tyre service.",
    specs: {
      Display: "Digital LCD",
      Accuracy: "High precision",
      Operation: "Air line connected",
      Usage: "Professional tyre service",
    },
    features: ["Digital accuracy", "Fast inflation", "Durable housing", "Workshop ready"],
    application: "Tyre service, pressure diagnostics",
    cta: "Request Quote",
    hsn: "9026",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "53",
    name: "Oil Pressure Tester Kit",
    sku: "OPT-KIT",
    category: "measurement",
    brand: "Blue Point",
    image: "/images/products/oil-pressure-tester-kit.jpg",
    description: "Professional oil pressure tester kit for engine lubrication diagnostics.",
    specs: {
      Gauge: "High accuracy",
      Range: "Wide pressure range",
      Adapters: "Multiple engine fittings",
      Use: "Engine diagnostics",
    },
    features: ["Accurate readings", "Multiple adapters", "Durable gauge", "Professional diagnostics"],
    application: "Engine diagnostics, lubrication testing",
    cta: "Request Quote",
    hsn: "9026",
    minOrderQty: 1,
    inStock: true,
  },

  // ==================== POWER & WORKSHOP MACHINES ====================
  {
    id: "54",
    name: "Bench Grinder Professional",
    sku: "BG-PRO",
    category: "power-tools",
    brand: "Bosch",
    image: "/images/products/bench-grinder-professional.jpg",
    description: "Professional bench grinder for sharpening, grinding, and workshop finishing tasks.",
    specs: {
      Motor: "High torque",
      Wheels: "Dual grinding wheels",
      Guard: "Safety shield",
      Usage: "Workshop grinding",
    },
    features: ["High torque motor", "Dual wheels", "Safety guards", "Professional durability"],
    application: "Tool sharpening, metal grinding",
    cta: "Request Quote",
    hsn: "8460",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "55",
    name: "Bosch Heat Gun Professional",
    sku: "BOSCH-HG",
    category: "power-tools",
    brand: "Bosch",
    image: "/images/products/bosch-heat-gun-professional.jpg",
    description: "Professional heat gun for paint removal, plastic shaping, and workshop applications.",
    specs: {
      Temperature: "Variable",
      Power: "High output",
      Control: "Electronic",
      Design: "Ergonomic",
    },
    features: ["Variable temperature", "High power", "Ergonomic grip", "Professional use"],
    application: "Paint removal, plastic shaping, workshop tasks",
    cta: "Request Quote",
    hsn: "8516",
    minOrderQty: 1,
    inStock: true,
  }

]

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.category === categoryId)
}

export function getProductsByBrand(brand: string): Product[] {
  return products.filter((p) => p.brand === brand)
}

export function getTopProducts(count = 10): Product[] {
  return products.slice(0, count)
}

export function getOfferProducts(): Product[] {
  return products.filter((p) => p.isOffer)
}

export function searchProducts(query: string): Product[] {
  const lowercaseQuery = query.toLowerCase()
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lowercaseQuery) ||
      p.description.toLowerCase().includes(lowercaseQuery) ||
      p.brand.toLowerCase().includes(lowercaseQuery) ||
      p.sku.toLowerCase().includes(lowercaseQuery),
  )
}
