export interface Product {
  id: string
  name: string
  sku: string
  price: number
  originalPrice?: number
  category: string
  brand: string
  image: string
  description: string
  specs: Record<string, string>
  hsn: string
  minOrderQty: number
  inStock: boolean
  isOffer?: boolean
  offerBadge?: string
}

export const categories = [
  { id: "hand-tools", name: "Hand Tools", icon: "🔧", description: "Wrenches, pliers, screwdrivers & more" },
  { id: "power-tools", name: "Power Tools", icon: "⚡", description: "Drills, grinders, saws & electric tools" },
  { id: "spray-guns", name: "Spray Guns & Painting Systems", icon: "🎨", description: "Professional spray equipment" },
  { id: "welding", name: "Welding Machines & Inverters", icon: "🔥", description: "MIG, TIG, Arc welders" },
  { id: "lifting", name: "Engine Cranes & Lifting Equipment", icon: "🏗️", description: "Cranes, hoists & jacks" },
  { id: "transmission", name: "Transmission Jacks & Stands", icon: "🚗", description: "Automotive lifting solutions" },
  { id: "special-tools", name: "Special Service Tools", icon: "🔩", description: "OEM & specialty tools" },
  { id: "pneumatic", name: "Pneumatic Tools & Compressors", icon: "💨", description: "Air-powered equipment" },
  { id: "stanley", name: "Stanley Tools", icon: "🛠️", description: "Premium Stanley brand tools" },
  { id: "bosch", name: "Bosch Tools", icon: "⚙️", description: "German engineering excellence" },
  { id: "measurement", name: "Measurement & Testing Tools", icon: "📏", description: "Gauges, calipers, testers" },
  { id: "painting", name: "Paint Booth & Infrared", icon: "💡", description: "Infrared booths & curing" },
]

export const brands = [
  "Bosch",
  "Stanley",
  "Blue Point",
  "DeWALT",
  "Mirka",
  "Mitutoyo",
  "Fluke",
  "JTC",
  "3M",
  "PCL",
  "Chicago Pneumatic",
  "Kärcher",
  "Rexter",
  "DeVilbiss",
  "Total",
  "Makita",
  "Generic Pro",
  "CAR-O-LINER",
  "SATA",
  "LINICH",
  "ACCURA",
  "MaxShine",
  "Menzerna",
]

export const products: Product[] = [
  // LINICH AUTO PULLER
  {
    id: "1",
    name: "Linich 3100 Auto Puller",
    sku: "LIN-3100",
    price: 85000,
    category: "special-tools",
    brand: "Generic Pro",
    image: "/images/products/1-linich-auto-puller.jpg",
    description:
      "Professional dent removal system with dual triggering modes (manual & automatic) for automotive body work",
    specs: {
      "Input Voltage": "220-230V AC",
      "Output Voltage": "7V AC",
      "Max Welding Output": "11 KVA",
      "Max Welding Current": "3000A",
      "Protection Rating": "IP 21",
      Weight: "29 kg",
      "Cable Length": "6m (3 core 2.5mm)",
      "Output Cable": "50mm x 3m",
      Dimensions: "H-235mm, W-260mm, L-375mm",
      Features: "Manual/Automatic triggering, German thyristor, Includes accessories",
    },
    hsn: "8508",
    minOrderQty: 1,
    inStock: true,
  },

  // SPOT WELDER LCR 70
  {
    id: "2",
    name: "Linich Spot Welder LCR 70",
    sku: "LCR-70",
    price: 145000,
    category: "welding",
    brand: "Generic Pro",
    image: "/images/products/2-spot-welder-lcr-70.jpg",
    description:
      "Heavy-duty spot welder and dent puller combo with spring balancer and temperature-controlled air cooling",
    specs: {
      Input: "400V AC, 50Hz",
      "Output Current": "13500A Max",
      "Output KVA": "47.3 KVA @ 50%",
      "Output Voltage": "7V (No-Load), 3V (Load)",
      "Rated Power Factor": "0.8",
      "Input Cable": "4mm² 3 core x 6m",
      Weight: "146 kg",
      Protection: "IP 22",
      Modes: "Single Spot, Dual Spot",
      "Coolant Tank": "1.5L @ 6 Bar",
      Dimensions: "2092 x 801 x 562mm",
      Features: "User-friendly panel, Spring balancer, Heavy duty rated",
    },
    hsn: "8515",
    minOrderQty: 1,
    inStock: true,
  },

  // AUTOMIG WELDER
  {
    id: "3",
    name: "AutoMig MW 250 XL MIG Welder",
    sku: "MW-250-XL",
    price: 125000,
    category: "welding",
    brand: "Generic Pro",
    image: "/images/products/3-automig-mw-250-xl-welder.jpg",
    description:
      "Three-phase MIG/MAG welding machine with optimized inductor for spatter-free welding and energy efficiency",
    specs: {
      Phase: "Three Phase",
      "Main Voltage": "440V 50/60Hz",
      "Output Current": "60-250 AMPS",
      "Max Welding": "6 KVA",
      "Welding Torch": "15 AK",
      "Wire Diameter": "0.8mm to 1.2mm",
      Weight: "70 kg",
      Features: "Step-regulated, Spatter-free, Energy efficient, Easily removable wheels",
    },
    hsn: "8515",
    minOrderQty: 1,
    inStock: true,
  },

  // 4-TON HYDRAULIC LIFT
  {
    id: "4",
    name: "4-Ton Hydraulic Two-Post Lift",
    sku: "LFT-4T",
    price: 185000,
    category: "lifting",
    brand: "Generic Pro",
    image: "/images/products/4-hydraulic-two-post-lift.jpg",
    description: "Professional two-post vehicle lift with symmetric/asymmetric arms and safety door opening pads",
    specs: {
      "Lifting Capacity": "4000 kg",
      "Lifting Height": "1900mm",
      "Machine Height": "3600mm",
      "Machine Width": "3400mm",
      "Inside Column Width": "2800mm",
      "Lifting Time": "55 seconds",
      "Lowering Time": "25 seconds",
      Motor: "2.2 KW",
      Power: "380V / 3 Phase",
      Construction: "5mm steel plates, 8mm brace arm, 6mm sliding column",
      Features: "Chrome plated cylinder, Italian seals, Aluminum motor, No deformity design",
    },
    hsn: "8428",
    minOrderQty: 1,
    inStock: true,
  },

  // AIR COMPRESSOR 30L
  {
    id: "5",
    name: "Linich Air Compressor 30L",
    sku: "LIN-30L",
    price: 18500,
    category: "pneumatic",
    brand: "Generic Pro",
    image: "/images/products/5-air-compressor-30l.jpg",
    description: "Compact dry/wet air compressor with recycle cooling for workshop use",
    specs: {
      Model: "LIN-30L",
      Capacity: "30 Liters",
      Power: "1200W",
      "Air Flow": "53 L/min",
      Function: "Dry/Wet",
      "Cooling Mode": "Recycle",
      "Gross Weight": "14.1 kg",
      Features: "Portable, Dual function, Efficient cooling",
    },
    hsn: "8414",
    minOrderQty: 1,
    inStock: true,
  },

  // AIR COMPRESSOR 80L
  {
    id: "6",
    name: "Linich Air Compressor 80L",
    sku: "LIN-80L",
    price: 35000,
    category: "pneumatic",
    brand: "Generic Pro",
    image: "/images/products/6-air-compressor-80l.jpg",
    description: "Heavy-duty dry/wet air compressor for industrial workshop applications",
    specs: {
      Model: "LIN-80L",
      Capacity: "80 Liters",
      Power: "3000W",
      "Air Flow": "106 L/min",
      Function: "Dry/Wet",
      "Cooling Mode": "Recycle",
      "Gross Weight": "27.8 kg",
      Features: "Industrial rated, High flow capacity, Efficient cooling",
    },
    hsn: "8414",
    minOrderQty: 1,
    inStock: true,
  },

  // TRANSMISSION JACK 1 TON
  {
    id: "7",
    name: "Transmission Jack 1 Ton",
    sku: "TJ-1T",
    price: 12000,
    category: "transmission",
    brand: "Generic Pro",
    image: "/images/products/7-transmission-jack-1ton.jpg",
    description: "Hydraulic transmission jack with adjustable saddle for safe transmission removal",
    specs: {
      Model: "TREL0501A",
      Capacity: "1 Ton",
      "Min Height": "860mm",
      "Max Height": "1835mm",
      "Weight (NW/GW)": "90 kg",
      Features: "Adjustable saddle, Safety valve, Smooth operation",
    },
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // TRANSMISSION JACK 2 TON
  {
    id: "8",
    name: "Transmission Jack 2 Ton",
    sku: "TJ-2T",
    price: 14500,
    category: "transmission",
    brand: "Generic Pro",
    image: "/images/products/8-transmission-jack-2ton.jpg",
    description: "Heavy-duty 2-ton hydraulic transmission jack with stabilizing base",
    specs: {
      Model: "T32222-GS",
      Capacity: "2 Ton",
      "Min Height": "1580mm",
      "Max Width": "1040mm",
      "Weight (NW/GW)": "74 kg",
      Features: "Wide base, Smooth hydraulics, Professional grade",
    },
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // ENGINE CRANE 0.5 TON
  {
    id: "9",
    name: "Engine Crane 0.5 Ton",
    sku: "EC-500",
    price: 9500,
    category: "lifting",
    brand: "Generic Pro",
    image: "/images/products/9-engine-crane-500kg.jpg",
    description: "Compact folding engine crane for light-duty engine lifting",
    specs: {
      Model: "TREL0501A",
      Capacity: "0.5-0.6 Ton",
      "Min Height": "1200mm",
      "Max Height": "1795mm",
      "Weight (NW/GW)": "41 kg",
      Features: "Lightweight, Portable, Easy to fold",
    },
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // HYDRAULIC PRESS 20 TON
  {
    id: "10",
    name: "Hydraulic Press 20 Ton",
    sku: "HP-20T",
    price: 32000,
    category: "special-tools",
    brand: "Generic Pro",
    image: "/images/products/10-hydraulic-press-20ton.jpg",
    description: "Precision hydraulic press for bearing and component work",
    specs: {
      Model: "KCSP20T-G",
      Capacity: "20 Ton",
      "Working Range": "0-955mm",
      Stroke: "154mm",
      "Bed Width": "550mm",
      Features: "Precision-engineered, Smooth operation, Industrial rated",
    },
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // HYDRAULIC PRESS 30 TON
  {
    id: "11",
    name: "Hydraulic Press 30 Ton",
    sku: "HP-30T",
    price: 45000,
    category: "special-tools",
    brand: "Generic Pro",
    image: "/images/products/11-hydraulic-press-30ton.jpg",
    description: "Heavy-duty 30-ton hydraulic press for demanding applications",
    specs: {
      Model: "KCSP30T-G",
      Capacity: "30 Ton",
      "Working Range": "0-1050mm",
      Stroke: "162mm",
      "Bed Width": "460mm",
      Features: "Heavy-duty rated, Precision hydraulics, Professional grade",
    },
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // VACUUM CLEANER
  {
    id: "12",
    name: "Vacuum Cleaner for Workshops",
    sku: "VC-IND",
    price: 22000,
    category: "pneumatic",
    brand: "Generic Pro",
    image: "/images/products/12-vacuum-cleaner.jpg",
    description: "Industrial workshop vacuum cleaner for dry and wet applications",
    specs: {
      Power: "3000W",
      "Suction Capacity": "High performance",
      Functions: "Dry/Wet cleaning",
      "Tank Type": "Heavy-duty",
      Features: "Industrial rated, Portable, Efficient filtration",
    },
    hsn: "8408",
    minOrderQty: 1,
    inStock: true,
  },

  // INFRARED PAINT BOOTH
  {
    id: "13",
    name: "Infrared Paint Booth 3000W",
    sku: "IPB-3000",
    price: 78000,
    category: "painting",
    brand: "Generic Pro",
    image: "/images/products/13-infrared-paint-booth.jpg",
    description: "Professional infrared curing booth with adjustable heat and automatic distance sensing",
    specs: {
      Model: "PL3000W",
      "Power Supply": "1Ph 230V",
      "Rated Power": "3000W",
      "Height Adjust": "0.2-2.1m",
      "Work Current": "13.6A",
      "Output Temperature": "40-80°C",
      Timer: "0.1-30 min",
      "Working Distance": "0.5-0.7m",
      Features: "Aluminum column, Philips lamp, Electronic timer, Auto distance sensor, Overload protection",
    },
    hsn: "8516",
    minOrderQty: 1,
    inStock: true,
  },

  // 5 TON FLOOR JACK
  {
    id: "14",
    name: "5 Ton Floor Jack",
    sku: "FJ-5T",
    price: 8500,
    category: "transmission",
    brand: "Generic Pro",
    image: "/images/products/14-5-ton-floor-jack.jpg",
    description: "Professional 5-ton hydraulic floor jack with quick-release mechanism",
    specs: {
      Capacity: "5 Tons",
      "Lifting Height": "Standard range",
      Wheels: "Swivel casters",
      Features: "Dual pump, Quick release, Safety valve, Maneuverable",
    },
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // BEARING PULLER SET
  {
    id: "15",
    name: "Bearing Puller Set",
    sku: "BP-SET",
    price: 5500,
    category: "hand-tools",
    brand: "Blue Point",
    image: "/images/products/15-bearing-puller-set.jpg",
    description: "6-piece bearing puller set with sizes from 75mm to 300mm",
    specs: {
      "Sizes Included": "75mm, 100mm, 150mm, 200mm, 250mm, 300mm",
      Material: "Hardened steel",
      Features: "Precise extraction, Multiple sizes, Professional grade",
    },
    hsn: "8205",
    minOrderQty: 1,
    inStock: true,
  },

  // FLUKE MULTIMETER
  {
    id: "16",
    name: "Fluke Digital Multimeter",
    sku: "FM-175",
    price: 8900,
    category: "measurement",
    brand: "Fluke",
    image: "/images/products/16-fluke-digital-multimeter.jpg",
    description: "Professional digital multimeter for electrical diagnostics and testing",
    specs: {
      Display: "Digital LCD",
      Functions: "Voltage, Current, Resistance, Temperature",
      Accuracy: "High precision",
      Features: "CAT III rated, Auto-ranging, Backlit display",
    },
    hsn: "9030",
    minOrderQty: 1,
    inStock: true,
  },

  // MITUTOYO MICROMETER
  {
    id: "17",
    name: "Mitutoyo Micrometer 25mm",
    sku: "MM-25",
    price: 4200,
    category: "measurement",
    brand: "Mitutoyo",
    image: "/images/products/17-mitutoyo-micrometer.jpg",
    description: "Precision micrometer for accurate measurements up to 25mm",
    specs: {
      Range: "0-25mm",
      Accuracy: "±0.01mm",
      Material: "Chrome plated steel",
      Features: "Precision-engineered, Easy reading, Professional grade",
    },
    hsn: "9031",
    minOrderQty: 1,
    inStock: true,
  },

  // SOCKET SET 25PC BLUE POINT
  {
    id: "18",
    name: "Socket Set 25PC Blue Point",
    sku: "SS-25BP",
    price: 3800,
    category: "hand-tools",
    brand: "Blue Point",
    image: "/images/products/18-socket-set-25pc.jpg",
    description: "Complete 25-piece socket set with ratchet and adapters",
    specs: {
      Pieces: "25",
      "Drive Size": '1/2"',
      "Socket Sizes": "Standard and metric",
      Material: "Chrome vanadium",
      Features: "Complete set, Blow molded case, Professional grade",
    },
    hsn: "8205",
    minOrderQty: 1,
    inStock: true,
  },

  // DEWALT ANGLE GRINDER
  {
    id: "19",
    name: "DeWALT Angle Grinder 800W",
    sku: "DW-AG800",
    price: 6800,
    category: "power-tools",
    brand: "DeWALT",
    image: "/images/products/19-dewalt-angle-grinder.jpg",
    description: "Professional 100mm angle grinder with variable speed control",
    specs: {
      Model: "GWS 800",
      Power: "800W",
      "Disc Diameter": "100mm",
      "No-load Speed": "11,000 rpm",
      Features: "Variable speed, Safety guard, Comfortable grip",
    },
    hsn: "8463",
    minOrderQty: 1,
    inStock: true,
  },

  // 3M SPRAY GUN
  {
    id: "20",
    name: "3M Performance Spray Gun",
    sku: "3M-SG",
    price: 12500,
    category: "spray-guns",
    brand: "3M",
    image: "/images/products/20-3m-performance-spray-gun.jpg",
    description: "Professional automotive spray gun with precision fluid delivery",
    specs: {
      Brand: "3M",
      Type: "HVLP compatible",
      "Fluid Capacity": "Standard cup",
      "Spray Pattern": "Adjustable",
      Features: "Precision nozzle, Ergonomic design, Professional finish",
    },
    hsn: "7311",
    minOrderQty: 1,
    inStock: true,
  },

  // REXTER PAINT GUN
  {
    id: "21",
    name: "Rexter Paint Gun Professional",
    sku: "REX-PG",
    price: 9800,
    category: "spray-guns",
    brand: "Rexter",
    image: "/images/products/21-rexter-paint-gun.jpg",
    description: "Heavy-duty paint sprayer for professional automotive finishing",
    specs: {
      Type: "Pressure feed",
      Nozzle: "Precision engineered",
      "Fluid Capacity": "1-liter cup",
      "Spray Pattern": "Adjustable width",
      Features: "Professional grade, Smooth finish, Durable construction",
    },
    hsn: "7311",
    minOrderQty: 1,
    inStock: true,
  },

  // CORDLESS DRILL STANLEY
  {
    id: "22",
    name: "Stanley Cordless Drill",
    sku: "ST-CD20",
    price: 5200,
    category: "power-tools",
    brand: "Stanley",
    image: "/images/products/22-stanley-cordless-drill.jpg",
    description: "Compact cordless drill with multiple speed settings and LED work light",
    specs: {
      Voltage: "20V",
      Chuck: "13mm keyless",
      Speeds: "2 speed (0-450/1500 rpm)",
      Modes: "Drill/Driver/Hammer",
      Features: "LED light, Compact design, Lightweight",
    },
    hsn: "8508",
    minOrderQty: 1,
    inStock: true,
  },

  // HEAT GUN
  {
    id: "23",
    name: "Heat Gun 1800W",
    sku: "HG-1800",
    price: 4500,
    category: "power-tools",
    brand: "Bosch",
    image: "/images/products/23-heat-gun.jpg",
    description: "Professional heat gun with variable temperature and air flow control",
    specs: {
      Power: "1800W",
      "Max Temperature": "350/550°C",
      "Air Flow": "350/550 LPM",
      Features: "Temperature selector, Variable speed, Ergonomic grip",
    },
    hsn: "8516",
    minOrderQty: 1,
    inStock: true,
  },

  // TYRE PRESSURE GAUGE
  {
    id: "24",
    name: "Digital Tyre Pressure Gauge",
    sku: "TPG-DIG",
    price: 2800,
    category: "measurement",
    brand: "PCL",
    image: "/images/products/24-digital-tyre-gauge.jpg",
    description: "Precision digital tyre pressure gauge with backlit LCD display",
    specs: {
      Display: "Digital LCD",
      Range: "0-150 PSI",
      Accuracy: "±1%",
      Features: "Auto-off, Backlit display, Fast reading",
    },
    hsn: "9030",
    minOrderQty: 1,
    inStock: true,
  },

  // PCL NITROGEN GENERATOR
  {
    id: "25",
    name: "PCL SUMO Nitrogen Generator",
    sku: "PCL-N2",
    price: 95000,
    category: "pneumatic",
    brand: "PCL",
    image: "/images/products/25-pcl-sumo-nitrogen-generator.jpg",
    description: "Mobile PSA nitrogen generation system for tyre inflation with preset pressure control",
    specs: {
      Technology: "PSA (Pressure Swing Adsorption)",
      Capacity: "High purity N2",
      Features: "Preset pressure, 4-tyre simultaneous inflate, Air/N2 selector, Mobile design",
      Applications: "Forecourt, workshop, fleet",
    },
    hsn: "8414",
    minOrderQty: 1,
    inStock: true,
  },

  // OIL PRESSURE TESTER JTC
  {
    id: "26",
    name: "Oil Pressure Tester JTC",
    sku: "JTC-OPT",
    price: 2200,
    category: "special-tools",
    brand: "JTC",
    image: "/images/products/26-oil-pressure-tester.jpg",
    description: "Diagnostic tool for engine oil pressure measurement",
    specs: {
      Type: "Mechanical gauge",
      Range: "0-100 PSI",
      Features: "Easy installation, Accurate reading, Professional grade",
    },
    hsn: "9030",
    minOrderQty: 1,
    inStock: true,
  },

  // DIGITAL TORQUE WRENCH
  {
    id: "27",
    name: "Digital Torque Wrench",
    sku: "DTW-PRO",
    price: 6500,
    category: "hand-tools",
    brand: "Blue Point",
    image: "/images/products/27-digital-torque-wrench.jpg",
    description: "Digital precision torque wrench with memory and data lock features",
    specs: {
      Range: "0-300 Nm",
      Accuracy: "±3%",
      Display: "Digital LCD",
      Features: "Data memory, Auto-off, Overload protection",
    },
    hsn: "8205",
    minOrderQty: 1,
    inStock: true,
  },

  // VERNIER CALIPER
  {
    id: "28",
    name: "Vernier Caliper Mitutoyo",
    sku: "VC-MIT",
    price: 1800,
    category: "measurement",
    brand: "Mitutoyo",
    image: "/images/products/28-vernier-caliper.jpg",
    description: "Precision stainless steel vernier caliper for external and internal measurements",
    specs: {
      Range: "0-150mm",
      Accuracy: "±0.05mm",
      Material: "Stainless steel",
      Features: "Easy reading, Durable, Professional grade",
    },
    hsn: "9031",
    minOrderQty: 1,
    inStock: true,
  },

  // Top 10 Most Sold
  {
    id: "29",
    name: "Bosch GWS 800 Angle Grinder",
    sku: "BOSCH-GWS800",
    price: 2999,
    originalPrice: 3499,
    category: "power-tools",
    brand: "Bosch",
    image: "/images/products/29-bosch-gws-800-angle-grinder.jpg",
    description: "800W professional angle grinder with 100mm disc. Perfect for cutting and grinding metal.",
    specs: { Power: "800W", "Disc Size": "100mm", RPM: "11000", Weight: "1.8kg" },
    hsn: "84672100",
    minOrderQty: 1,
    inStock: true,
    isOffer: true,
    offerBadge: "Best Seller",
  },
  {
    id: "30",
    name: "Devilbiss GTI Pro Spray Gun",
    sku: "DVB-GTIPRO",
    price: 8500,
    originalPrice: 9500,
    category: "spray-guns",
    brand: "Devilbiss",
    image: "/images/products/30-devilbiss-gti-pro-spray-gun.jpg",
    description: "Professional HVLP spray gun for automotive painting. Superior atomization.",
    specs: { Nozzle: "1.3mm", Cup: "600ml", Pressure: "2 bar", Pattern: "280mm" },
    hsn: "84242000",
    minOrderQty: 1,
    inStock: true,
    isOffer: true,
    offerBadge: "Popular",
  },
  {
    id: "31",
    name: "Stanley 68-Piece Mechanics Tool Set",
    sku: "STN-68PC",
    price: 4200,
    category: "hand-tools",
    brand: "Stanley",
    image: "/images/products/31-stanley-68-piece-mechanics-tool-set.jpg",
    description: "Complete chrome vanadium tool set for professional mechanics.",
    specs: { Pieces: "68", Material: "Chrome Vanadium", Case: "Blow Mold", Drive: '1/4" & 1/2"' },
    hsn: "82055900",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "32",
    name: "Blue Point MIG Inverter Welder 200A",
    sku: "BP-MIG200",
    price: 12000,
    originalPrice: 14500,
    category: "welding",
    brand: "Blue Point",
    image: "/images/products/32-blue-point-mig-inverter-welder.jpg",
    description: "Professional MIG welder with inverter technology. Suitable for body shop work.",
    specs: { Current: "200A", Voltage: "230V", "Duty Cycle": "60%", Wire: "0.8-1.0mm" },
    hsn: "85153100",
    minOrderQty: 1,
    inStock: true,
    isOffer: true,
    offerBadge: "Hot Deal",
  },
  {
    id: "33",
    name: "Heavy Duty Tyre Inflator 12V",
    sku: "TI-HD12V",
    price: 1800,
    category: "pneumatic",
    brand: "Generic Pro",
    image: "/images/products/33-heavy-duty-tyre-inflator.jpg",
    description: "Digital tyre inflator with auto-cut feature. Suitable for all vehicle types.",
    specs: { Voltage: "12V DC", "Max PSI": "150", Display: "Digital", Cable: "3m" },
    hsn: "84148090",
    minOrderQty: 2,
    inStock: true,
  },
  {
    id: "34",
    name: "2 Ton Engine Crane Hydraulic",
    sku: "EC-2TON",
    price: 25000,
    category: "lifting",
    brand: "Generic Pro",
    image: "/images/products/34-2-ton-engine-crane.jpg",
    description: "Foldable hydraulic engine crane. Essential for engine removal and installation.",
    specs: { Capacity: "2 Ton", "Max Height": "2.3m", Type: "Foldable", Pump: "Hydraulic" },
    hsn: "84254900",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "35",
    name: "Dial Gauge Indicator 0-10mm",
    sku: "DG-010MM",
    price: 750,
    category: "measurement",
    brand: "Generic Pro",
    image: "/images/products/35-dial-gauge-indicator.jpg",
    description: "Precision dial gauge for runout and alignment measurements.",
    specs: { Range: "0-10mm", Resolution: "0.01mm", Dial: "58mm", Accuracy: "±0.02mm" },
    hsn: "90173000",
    minOrderQty: 5,
    inStock: true,
  },
  {
    id: "36",
    name: "Bosch GSB 500 RE Impact Drill",
    sku: "BOSCH-GSB500",
    price: 3500,
    category: "power-tools",
    brand: "Bosch",
    image: "/images/products/36-bosch-gsb-500-re-impact-drill.jpg",
    description: "500W reversible impact drill for professional use.",
    specs: { Power: "500W", Chuck: "13mm", RPM: "2800", "Impact Rate": "44800/min" },
    hsn: "84672100",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "37",
    name: 'Pneumatic Impact Wrench 1/2"',
    sku: "PIW-12IN",
    price: 4500,
    category: "pneumatic",
    brand: "Total",
    image: "/images/products/37-pneumatic-impact-wrench.jpg",
    description: "Heavy duty pneumatic impact wrench for tyre service and assembly.",
    specs: { Drive: '1/2"', Torque: "680 Nm", RPM: "7000", Air: "6.2 CFM" },
    hsn: "84672910",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "38",
    name: "Socket Set 46 Pieces Chrome",
    sku: "SS-46PC",
    price: 2200,
    category: "hand-tools",
    brand: "Stanley",
    image: "/images/products/38-socket-set-46-pieces.jpg",
    description: "Professional 46-piece socket set in plastic case.",
    specs: { Pieces: "46", Drive: '1/4" & 3/8"', Material: "Chrome Vanadium", Finish: "Mirror Polish" },
    hsn: "82041100",
    minOrderQty: 1,
    inStock: true,
  },
  // Additional products
  {
    id: "39",
    name: "Devilbiss FLG-5 Gravity Spray Gun",
    sku: "DVB-FLG5",
    price: 6500,
    category: "spray-guns",
    brand: "Devilbiss",
    image: "/images/products/39-devilbiss-flg-5-spray-gun.jpg",
    description: "Entry-level gravity feed spray gun for automotive refinishing.",
    specs: { Nozzle: "1.4mm", Cup: "600ml", Type: "Gravity Feed", Weight: "450g" },
    hsn: "84242000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "40",
    name: "Transmission Jack 0.5 Ton",
    sku: "TJ-05TON",
    price: 18000,
    category: "transmission",
    brand: "Generic Pro",
    image: "/images/products/40-transmission-jack-05-ton.jpg",
    description: "Low profile transmission jack for under-vehicle service.",
    specs: { Capacity: "0.5 Ton", "Min Height": "85cm", "Max Height": "175cm", Wheels: "4" },
    hsn: "84254900",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "41",
    name: "Bosch GBH 220 Rotary Hammer",
    sku: "BOSCH-GBH220",
    price: 8900,
    category: "power-tools",
    brand: "Bosch",
    image: "/images/products/41-bosch-gbh-220-rotary-hammer.jpg",
    description: "720W SDS Plus rotary hammer for concrete drilling.",
    specs: { Power: "720W", "Impact Energy": "2.0J", Chuck: "SDS Plus", Weight: "2.3kg" },
    hsn: "84672100",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "42",
    name: "Air Compressor 50L Tank",
    sku: "AC-50L",
    price: 15500,
    category: "pneumatic",
    brand: "Total",
    image: "/images/products/42-air-compressor-50l-tank.jpg",
    description: "Oil-free air compressor with 50L tank for workshop use.",
    specs: { Tank: "50L", Power: "2HP", Pressure: "8 bar", Flow: "200 L/min" },
    hsn: "84148010",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "43",
    name: "LINICH 3100 Auto Puller",
    sku: "LIN-3100AP",
    price: 45000,
    category: "special-tools",
    brand: "LINICH",
    image: "/images/products/43-linich-3100-auto-puller.jpg",
    description:
      "Professional automatic dent puller machine with manual and automatic triggering modes. Perfect for straightening vehicle body.",
    specs: {
      "Input Voltage": "220-230V AC",
      "Max Welding Current": "3000A",
      "Max Output": "11 KVA",
      "Protection Rating": "IP 21",
      Weight: "29 Kg",
      "Triggering Modes": "Manual & Automatic",
    },
    hsn: "85043000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "44",
    name: "CRX Spot Welder CTR 9",
    sku: "CRX-CTR9",
    price: 28000,
    category: "welding",
    brand: "Blue Point",
    image: "/images/products/44-crx-spot-welder-ctr-9.jpg",
    description: "Professional spot welding machine with German-made thyristor technology. Ideal for body shop work.",
    specs: {
      "Output Voltage": "7V AC",
      "Max Current": "3000A",
      KVA: "11 KVA",
      Weight: "29 Kg",
      "Cable Length": "6m (3 core 2.5mm)",
      Protection: "IP 21",
    },
    hsn: "85043000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "45",
    name: "LINICH Spot Welder LCR 70",
    sku: "LIN-LCR70",
    price: 65000,
    originalPrice: 75000,
    category: "welding",
    brand: "LINICH",
    image: "/images/products/45-linich-spot-welder-lcr-70.jpg",
    description: "Heavy duty spot welder and dent puller combination. Temperature controlled air-cooled system.",
    specs: {
      Input: "400 VAC - 50 Hz",
      "Output Current": "13500A Imax",
      "Output KVA": "47.3 KVA @ 50%",
      Modes: "Single & Dual Spot",
      Weight: "146 kg",
      "Coolant Tank": "1.5 ltr at 6 Bar",
    },
    hsn: "85043000",
    minOrderQty: 1,
    inStock: true,
    isOffer: true,
  },
  {
    id: "46",
    name: "AutoMIG 250 XL MIG Welder",
    sku: "AUTOMIG-250XL",
    price: 55000,
    category: "welding",
    brand: "Generic Pro",
    image: "/images/products/46-automig-250-xl-mig-welder.jpg",
    description:
      "High performance MIG/MAG welding machine with optimized inductor for spatter-free welding. 3-phase 440V.",
    specs: {
      Phase: "3 Phase",
      "Main Voltage": "440V 50/60Hz",
      "Output Current": "60-250 AMPS",
      "Max Welding": "6 KVA",
      "Wire Size": "0.8-1.2 mm",
      Weight: "70 Kg",
    },
    hsn: "85044000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "47",
    name: "4 Ton Hydraulic Two Post Lift",
    sku: "HYD-2POST4T",
    price: 125000,
    originalPrice: 145000,
    category: "lifting",
    brand: "Total",
    image: "/images/products/47-4-ton-hydraulic-two-post-lift.jpg",
    description: "Heavy duty 4-ton capacity hydraulic two-post lift. Symmetric/asymmetric arms with door opening pads.",
    specs: {
      "Lifting Capacity": "4000 kgs",
      "Max Height": "1900 mm",
      "Machine Height": "3600 mm",
      "Machine Width": "3400 mm",
      Motor: "2.2 Kw",
      Power: "380V / 3 Phase",
    },
    hsn: "84281000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "48",
    name: "5 Ton Floor Jack",
    sku: "FLR-JACK5T",
    price: 8500,
    category: "lifting",
    brand: "Total",
    image: "/images/products/48-5-ton-floor-jack.jpg",
    description: "Professional 5-ton floor jack with dual pumps for quick lifting. Large foot pedal and wheels.",
    specs: {
      Capacity: "5 Ton",
      "Dual Pump": "Quick Lifting",
      "Large Wheels": "Easy Maneuverability",
      Safety: "Pressure Relief Valve",
      Material: "Steel with PU Protection",
    },
    hsn: "84861000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "49",
    name: "Transmission Jack 1 Ton",
    sku: "TRANS-JACK1T",
    price: 12000,
    category: "transmission",
    brand: "Total",
    image: "/images/products/49-transmission-jack-1-ton.jpg",
    description: "Professional transmission jack with 1-ton capacity. Min height 860mm, max 1835mm.",
    specs: {
      Capacity: "1 Ton",
      "Min Height": "860 mm",
      "Max Height": "1835 mm",
      Weight: "90 Kg",
      Material: "Steel",
    },
    hsn: "84861000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "50",
    name: "Hydraulic Press 20 Ton",
    sku: "HYD-PRESS20",
    price: 35000,
    category: "special-tools",
    brand: "Total",
    image: "/images/products/50-hydraulic-press-20-ton.jpg",
    description: "Industrial 20-ton hydraulic press. Stroke 154mm, bed width 550mm.",
    specs: {
      Capacity: "20 Ton",
      "Working Range": "0-955 mm",
      Stroke: "154 mm",
      "Bed Width": "550 mm",
      Weight: "Heavy Duty",
    },
    hsn: "84866000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "51",
    name: "Air Compressor 30L",
    sku: "AIR-COMP30L",
    price: 18000,
    category: "pneumatic",
    brand: "Generic Pro",
    image: "/images/products/51-air-compressor-30l.jpg",
    description: "Professional 30L air compressor with 1200W motor. Dry/wet function with recycled cooling.",
    specs: {
      Capacity: "30 Ltr",
      Power: "1200 W",
      "Air Flow": "53 L/min",
      Functions: "Dry/Wet Recycled",
      Weight: "14.1 kg",
    },
    hsn: "84148000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "52",
    name: "Infrared Heat Gun 3000W",
    sku: "HEAT-GUN3K",
    price: 22000,
    category: "special-tools",
    brand: "Generic Pro",
    image: "/images/products/52-infrared-heat-gun-3000w.jpg",
    description: "Industrial infrared heat lamp with 3 halogen lamps. 40-80°C temperature range with electronic timer.",
    specs: {
      Power: "3000 W (3 Lamps)",
      Height: "0.2-2.1 m (Adjustable)",
      Temperature: "40-80°C",
      Timer: "0.1-30 min",
      "Working Distance": "0.5-0.7 m",
    },
    hsn: "84798000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "53",
    name: "DeWALT Angle Grinder 800W",
    sku: "DEWALT-GWS800",
    price: 3500,
    category: "power-tools",
    brand: "Dewalt",
    image: "/images/products/53-dewalt-angle-grinder-800w.jpg",
    description: "800W professional angle grinder. 100mm disc with 11000 RPM.",
    specs: {
      Power: "800W",
      "Disc Diameter": "100 mm",
      "No-Load Speed": "11,000 rpm",
      Weight: "1.8 kg",
    },
    hsn: "84672100",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "54",
    name: "Mirka Orbital Sander",
    sku: "MIRKA-SAND",
    price: 6500,
    category: "power-tools",
    brand: "Mirka",
    image: "/images/products/54-mirka-orbital-sander.jpg",
    description: "Professional orbital sander with dust-free sanding technology. 150mm sanding plate.",
    specs: {
      "Sanding Plate": "150 mm",
      Power: "1250 W",
      Speed: "750-3000 rpm",
      "Dust Collection": "Yes",
      Weight: "2.5 kg",
    },
    hsn: "84672100",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "55",
    name: "3M Performance Spray Gun",
    sku: "3M-SPRAYGUN",
    price: 9500,
    category: "spray-guns",
    brand: "3M",
    image: "/images/products/55-3m-performance-spray-gun.jpg",
    description: "Professional automotive spray gun by 3M. Trusted by bodyshops worldwide.",
    specs: {
      Nozzle: "1.3-1.4 mm",
      "Cup Capacity": "600-700 ml",
      "Pattern Width": "280 mm",
      "Atomizing Air": "Adjustable",
    },
    hsn: "84242000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "56",
    name: "Fluke Digital Multimeter",
    sku: "FLUKE-MULTI",
    price: 8000,
    category: "special-tools",
    brand: "Fluke",
    image: "/images/products/56-fluke-digital-multimeter.jpg",
    description: "Professional digital multimeter by Fluke. Precision measurement for electrical diagnostics.",
    specs: {
      Display: "4000 Count",
      Functions: "AC/DC Voltage, Current, Resistance",
      Accuracy: "High Precision",
      Rugged: "Industrial Grade",
    },
    hsn: "90330000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "57",
    name: "Mitutoyo Micrometer",
    sku: "MITUTOYO-MIC",
    price: 4500,
    category: "hand-tools",
    brand: "Mitutoyo",
    image: "/images/products/57-mitutoyo-micrometer.jpg",
    description: "Precision micrometer by Mitutoyo. Accurate to 0.01mm.",
    specs: {
      Range: "0-25 mm",
      Accuracy: "±0.004 mm",
      Graduation: "0.01 mm",
      Material: "Hardened Steel",
    },
    hsn: "90310000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "58",
    name: "PCL Nitrogen Generator Inflator",
    sku: "PCL-NITROGEN",
    price: 65000,
    category: "pneumatic",
    brand: "PCL",
    image: "/images/products/58-pcl-nitrogen-generator-inflator.jpg",
    description: "PCL Sumo Nitrogen Generator with automatic tire inflation. 4-tire simultaneous inflation.",
    specs: {
      Technology: "PSA Process",
      Capacity: "Simultaneous 4 Tires",
      "Preset Function": "Yes",
      Purity: "High N2 Levels",
    },
    hsn: "84148000",
    minOrderQty: 1,
    inStock: true,
  },
  // More products to reach 50+
  {
    id: "59",
    name: "Creeper Mechanic 6-Wheel",
    sku: "MC-6W",
    price: 2800,
    category: "special-tools",
    brand: "Generic Pro",
    image: "/images/products/59-creeper-mechanic-6-wheel.jpg",
    description: "Padded mechanic creeper with 6 casters for smooth movement.",
    specs: { Wheels: "6", Padding: '2" Foam', Capacity: "150kg", Length: "100cm" },
    hsn: "94019090",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "60",
    name: 'Torque Wrench 1/2" 40-210Nm',
    sku: "TW-210NM",
    price: 3800,
    category: "hand-tools",
    brand: "Blue Point",
    image: "/images/products/60-torque-wrench-1-2-inch-40-210nm.jpg",
    description: "Click-type torque wrench for precise fastening.",
    specs: { Drive: '1/2"', Range: "40-210Nm", Accuracy: "±4%", Length: "45cm" },
    hsn: "82042000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "61",
    name: "Air Die Grinder Kit",
    sku: "ADG-KIT",
    price: 2500,
    category: "pneumatic",
    brand: "Total",
    image: "/images/products/61-air-die-grinder-kit.jpg",
    description: "Air die grinder with accessory kit for grinding and polishing.",
    specs: { Collet: "6mm", RPM: "25000", Air: "4 CFM", Accessories: "15pc" },
    hsn: "84672910",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "62",
    name: "SATA Spray Gun RS",
    sku: "SATA-RS",
    price: 22000,
    category: "spray-guns",
    brand: "Devilbiss",
    image: "/images/products/62-sata-spray-gun-rs.jpg",
    description: "Premium HVLP spray gun for high-end automotive finishing.",
    specs: { Nozzle: "1.3mm", Technology: "HVLP", Cup: "600ml", Origin: "Germany" },
    hsn: "84242000",
    minOrderQty: 1,
    inStock: true,
    isOffer: true,
    offerBadge: "Premium",
  },
  {
    id: "63",
    name: "Spot Welder 400A",
    sku: "SW-400A",
    price: 45000,
    category: "welding",
    brand: "Blue Point",
    image: "/images/products/63-spot-welder-400a.jpg",
    description: "Industrial spot welder for body panel repair.",
    specs: { Current: "400A", "Arm Length": "40cm", Timer: "Digital", Cooling: "Water" },
    hsn: "85153900",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "64",
    name: "Spring Compressor Set",
    sku: "SCS-01",
    price: 5500,
    category: "special-tools",
    brand: "Generic Pro",
    image: "/images/products/64-spring-compressor-set.jpg",
    description: "Heavy duty spring compressor for MacPherson struts.",
    specs: { Type: "Coil Spring", "Max Opening": "300mm", Material: "Forged Steel", Safety: "Lock Pins" },
    hsn: "82079010",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "65",
    name: 'Bench Grinder 6" 250W',
    sku: "BG-6IN",
    price: 3200,
    category: "power-tools",
    brand: "Bosch",
    image: "/images/products/65-bench-grinder-6-inch-250w.jpg",
    description: "Double wheel bench grinder for sharpening and deburring.",
    specs: { Wheel: '6" (150mm)', Power: "250W", RPM: "2950", Wheels: "2" },
    hsn: "84602100",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "66",
    name: "Engine Stand 450kg",
    sku: "ES-450",
    price: 8500,
    category: "lifting",
    brand: "Generic Pro",
    image: "/images/products/66-engine-stand-450kg.jpg",
    description: "Rotating engine stand for engine rebuilding.",
    specs: { Capacity: "450kg", Rotation: "360°", Head: "Adjustable", Wheels: "4" },
    hsn: "84254900",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "67",
    name: "Pressure Washer 130 Bar",
    sku: "PW-130",
    price: 12500,
    category: "spray-guns",
    brand: "Bosch",
    image: "/images/products/67-pressure-washer-130-bar.jpg",
    description: "High pressure washer for vehicle and equipment cleaning.",
    specs: { Pressure: "130 bar", Flow: "420 L/h", Power: "1700W", Hose: "6m" },
    hsn: "84243000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "68",
    name: "Multimeter Digital Auto",
    sku: "DMM-AUTO",
    price: 1850,
    category: "special-tools",
    brand: "Generic Pro",
    image: "/images/products/68-multimeter-digital-auto.jpg",
    description: "Auto-ranging digital multimeter for electrical diagnostics.",
    specs: { Display: "4000 Count", Range: "Auto", Functions: "AC/DC V, A, Ω", CAT: "III" },
    hsn: "90303390",
    minOrderQty: 2,
    inStock: true,
  },
  // More products to reach 50+
  {
    id: "69",
    name: "Pry Bar Set 4pc",
    sku: "PBS-4PC",
    price: 1200,
    category: "hand-tools",
    brand: "Stanley",
    image: "/images/products/69-pry-bar-set-4pc.jpg",
    description: "4-piece pry bar set for panel removal and leverage.",
    specs: { Pieces: "4", Sizes: '6"-24"', Material: "Hardened Steel", Handle: "Cushion Grip" },
    hsn: "82055900",
    minOrderQty: 2,
    inStock: true,
  },
  {
    id: "70",
    name: "Paint Mixing System Cups",
    sku: "PMS-50",
    price: 2200,
    category: "spray-guns",
    brand: "Devilbiss",
    image: "/images/products/70-paint-mixing-system-cups.jpg",
    description: "50-pack disposable paint mixing cups with lids.",
    specs: { Quantity: "50", Capacity: "600ml", Lid: "Included", Scale: "Printed Ratios" },
    hsn: "39241090",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "71",
    name: "Plasma Cutter 40A",
    sku: "PC-40A",
    price: 18500,
    category: "welding",
    brand: "Total",
    image: "/images/products/71-plasma-cutter-40a.jpg",
    description: "Inverter plasma cutter for clean metal cutting.",
    specs: { Current: "40A", "Cut Thickness": "12mm", Air: "3.5 CFM", Weight: "8kg" },
    hsn: "85159000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "72",
    name: "Oil Filter Wrench Set",
    sku: "OFWS-01",
    price: 850,
    category: "special-tools",
    brand: "Generic Pro",
    image: "/images/products/72-oil-filter-wrench-set.jpg",
    description: "Universal oil filter wrench set for various filter sizes.",
    specs: { Type: "Cap Style", Sizes: "65-100mm", Pieces: "5", Drive: '3/8"' },
    hsn: "82041100",
    minOrderQty: 2,
    inStock: true,
  },
  {
    id: "73",
    name: "Heat Gun 2000W",
    sku: "HG-2000",
    price: 2800,
    category: "power-tools",
    brand: "Bosch",
    image: "/images/products/73-heat-gun-2000w.jpg",
    description: "Variable temperature heat gun for paint stripping and shrinking.",
    specs: { Power: "2000W", Temp: "50-630°C", Flow: "500 L/min", Stages: "Variable" },
    hsn: "84162000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "74",
    name: "Bearing Puller Set 3-Jaw",
    sku: "BPS-3JAW",
    price: 2400,
    category: "special-tools",
    brand: "Generic Pro",
    image: "/images/products/74-bearing-puller-set-3-jaw.jpg",
    description: "3-jaw bearing puller set for extracting bearings and gears.",
    specs: { Pieces: "3", Sizes: "75-150mm", Jaws: "Reversible", Material: "Chrome Vanadium" },
    hsn: "82079010",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "75",
    name: "Workshop Stool Pneumatic",
    sku: "WS-PNEU",
    price: 3500,
    category: "special-tools",
    brand: "Generic Pro",
    image: "/images/products/75-workshop-stool-pneumatic.jpg",
    description: "Height adjustable pneumatic workshop stool with storage.",
    specs: { Height: "43-58cm", Seat: "36cm", Capacity: "136kg", Casters: "5" },
    hsn: "94017900",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "76",
    name: "Air Blow Gun Set",
    sku: "ABG-SET",
    price: 450,
    category: "pneumatic",
    brand: "Total",
    image: "/images/products/76-air-blow-gun-set.jpg",
    description: "Air blow gun with multiple nozzle attachments.",
    specs: { Nozzles: "5", Inlet: '1/4" BSP', Body: "Aluminum", Trigger: "Ergonomic" },
    hsn: "84818090",
    minOrderQty: 5,
    inStock: true,
  },
  {
    id: "77",
    name: 'Magnetic Tool Holder 18"',
    sku: "MTH-18",
    price: 650,
    category: "hand-tools",
    brand: "Stanley",
    image: "/images/products/77-magnetic-tool-holder-18.jpg",
    description: "Wall-mount magnetic strip for tool organization.",
    specs: { Length: '18"', Magnet: "Strong Hold", Mount: "Screws Included", Capacity: "6kg" },
    hsn: "85051900",
    minOrderQty: 3,
    inStock: true,
  },
  {
    id: "78",
    name: "Body Repair Dent Puller Kit",
    sku: "BRDP-KIT",
    price: 8500,
    category: "special-tools",
    brand: "Blue Point",
    image: "/images/products/78-body-repair-dent-puller-kit.jpg",
    description: "Complete body dent repair kit with slide hammer.",
    specs: { Type: "Slide Hammer", Attachments: "12", Use: "Body Repair", Case: "Metal Box" },
    hsn: "82079010",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "79",
    name: "Jigsaw 600W Variable Speed",
    sku: "JS-600V",
    price: 4500,
    category: "power-tools",
    brand: "Bosch",
    image: "/images/products/79-jigsaw-600w-variable-speed.jpg",
    description: "Variable speed jigsaw for curves and intricate cuts.",
    specs: { Power: "600W", SPM: "500-3100", Stroke: "23mm", Bevel: "45°" },
    hsn: "84672200",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "80",
    name: "Grease Gun Heavy Duty",
    sku: "GG-HD",
    price: 1100,
    category: "hand-tools",
    brand: "Generic Pro",
    image: "/images/products/80-grease-gun-heavy-duty.jpg",
    description: "Lever-type grease gun for lubrication.",
    specs: { Type: "Lever", Capacity: "500ml", Pressure: "400 bar", Hose: "Flexible" },
    hsn: "84819090",
    minOrderQty: 2,
    inStock: true,
  },
  {
    id: "81",
    name: "Safety Glasses Clear 12 Pack",
    sku: "SG-12PK",
    price: 950,
    category: "special-tools",
    brand: "Generic Pro",
    image: "/images/products/81-safety-glasses-clear-12-pack.jpg",
    description: "Anti-scratch safety glasses bulk pack.",
    specs: { Quantity: "12", Lens: "Polycarbonate", UV: "Protection", Standard: "EN166" },
    hsn: "90049000",
    minOrderQty: 1,
    inStock: true,
  },
  {
    id: "82",
    name: "Hydraulic Press 12 Ton",
    sku: "HP-12TON",
    price: 35000,
    category: "lifting",
    brand: "Generic Pro",
    image: "/images/products/82-hydraulic-press-12-ton.jpg",
    description: "Floor-standing hydraulic shop press.",
    specs: { Capacity: "12 Ton", Height: "150cm", "Bed Width": "53cm", Stroke: "15cm" },
    hsn: "84629900",
    minOrderQty: 1,
    inStock: false,
  },
  {
    id: "83",
    name: "Battery Charger 12/24V Smart",
    sku: "BC-SMART",
    price: 4500,
    category: "special-tools",
    brand: "Total",
    image: "/images/products/83-battery-charger-12-24v-smart.jpg",
    description: "Smart battery charger with maintenance mode.",
    specs: { Voltage: "12/24V", Current: "15A", Display: "LCD", Mode: "Smart Charge" },
    hsn: "85044030",
    minOrderQty: 1,
    inStock: true,
  },

  // 1. Blue-Point Multifunction Dent Pulling Machine
  {
    id: "bp-dent-01",
    name: "Blue-Point Multifunction Dent Pulling Machine",
    sku: "BP-MDPM",
    price: 95000,
    category: "special-tools",
    brand: "Blue Point",
    image: "/images/products/bp-dent-01-blue-point-dent-machine.jpg",
    description:
      "Professional dent pulling machine for thin car body panels. Minimizes metal distortion with time-controlled welding.",
    specs: {
      "Input Voltage": "220V / 380V",
      Frequency: "50 / 60 Hz",
      "Rated Input Power": "11.5 KVA",
      "Max Welding Current": "1800 A",
      "Welding Time": "0-99 seconds",
      "Standard Accessories": "Dent pulling hammer, Welding gun, Accessories box",
      Applications: "Automotive body repair, Collision repair centers",
    },
    hsn: "8515",
    minOrderQty: 1,
    inStock: true,
  },

  // 2. Blue-Point Inverter MIG Welder 160A
  {
    id: "bp-mig-160",
    name: "Blue-Point Inverter MIG Welder 160A",
    sku: "BP-MIG160",
    price: 42000,
    category: "welding",
    brand: "Blue Point",
    image: "/images/products/bp-mig-160-blue-point-mig-welder.jpg",
    description: "Dual-function MIG & MMA welding machine with IGBT inverter technology for professional workshop use.",
    specs: {
      "Input Voltage": "230V ±15%",
      "Output Current": "Up to 160A",
      "Duty Cycle": "40%",
      "Wire Diameter": "0.8 – 1.2 mm",
      Technology: "IGBT Inverter",
      "Power Efficiency": "High",
      Applications: "Automotive fabrication, General workshop welding",
    },
    hsn: "8515",
    minOrderQty: 1,
    inStock: true,
  },

  // 3. CAR-O-LINER CTR-9 Inverter Spot Welder
  {
    id: "car-o-ctr9",
    name: "CAR-O-LINER CTR-9 Inverter Spot Welder",
    sku: "CAR-CTR9",
    price: 185000,
    category: "welding",
    brand: "CAR-O-LINER",
    image: "/images/products/car-o-ctr9-car-o-liner-spot-welder.jpg",
    description:
      "Lightweight inverter spot welder with ergonomic design for collision repair. Features CANBUS communication.",
    specs: {
      Technology: "Inverter-based",
      "Gun Type": "Lightweight transformer",
      Handle: "Ergonomic swivel",
      Communication: "CANBUS precision control",
      "Energy Consumption": "Low",
      Design: "Compact with excellent mobility",
      "Welding Cycles": "Fast",
    },
    hsn: "8515",
    minOrderQty: 1,
    inStock: true,
  },

  // 4. CAR-O-LINER CRX Spot Welder
  {
    id: "car-o-crx",
    name: "CAR-O-LINER CRX Spot Welder",
    sku: "CAR-CRX",
    price: 165000,
    category: "welding",
    brand: "CAR-O-LINER",
    image: "/images/products/car-o-crx-car-o-liner-spot-welder.jpg",
    description: "Inverter-based spot welder with lightweight and compact design for collision repair centers.",
    specs: {
      Technology: "Inverter-based",
      Weight: "Lightweight",
      Design: "Compact",
      Mobility: "High",
      Operation: "Easy",
      Performance: "Stable welding",
      "Power Consumption": "Reduced",
    },
    hsn: "8515",
    minOrderQty: 1,
    inStock: true,
  },

  // 5. SATAjet 1000 IC Paint Spray Gun
  {
    id: "sata-jet1000",
    name: "SATAjet 1000 IC Paint Spray Gun",
    sku: "SATA-1000IC",
    price: 28000,
    category: "spray-guns",
    brand: "SATA",
    image: "/images/products/sata-jet1000-sata-paint-spray-gun.jpg",
    description:
      "Premium German-engineered spray gun for solvent and water-based automotive coatings with superior atomization.",
    specs: {
      "Air Distribution": "Precision system",
      "Transfer Efficiency": "High",
      "Nozzle Design": "Optimized",
      Construction: "Ergonomic and balanced",
      "Paint Consumption": "Reduced",
      Finish: "Consistent professional",
      Applications: "Automotive refinishing, High-end work",
    },
    hsn: "7311",
    minOrderQty: 1,
    inStock: true,
  },

  // 6. DeVilbiss DV1 Basecoat Spray Gun
  {
    id: "devilbiss-dv1",
    name: "DeVilbiss DV1 Basecoat Spray Gun",
    sku: "DVB-DV1",
    price: 18500,
    category: "spray-guns",
    brand: "DeVilbiss",
    image: "/images/products/devilbiss-dv1-basecoat-spray-gun.jpg",
    description:
      "Professional basecoat spray gun with exceptional atomization and control for modern automotive coatings.",
    specs: {
      Body: "Lightweight balanced",
      "Material Transfer": "High efficiency",
      Overspray: "Minimal waste",
      Coating: "Modern automotive compatible",
      Performance: "Consistent paint application",
      Applications: "Professional refinishing",
    },
    hsn: "7311",
    minOrderQty: 1,
    inStock: true,
  },

  // 7. DeVilbiss ProLite Spray Gun
  {
    id: "devilbiss-prolite",
    name: "DeVilbiss ProLite Spray Gun",
    sku: "DVB-PROLITE",
    price: 22000,
    category: "spray-guns",
    brand: "DeVilbiss",
    image: "/images/products/devilbiss-prolite-spray-gun.jpg",
    description: "Professional spray gun with forged aluminum body for maximum atomization efficiency and durability.",
    specs: {
      Body: "Forged aluminum",
      "Fluid Nozzle": "Stainless steel",
      "Spray Pattern": "Excellent consistency",
      "Service Life": "Long duration",
      Applications: "Demanding automotive paint environments",
    },
    hsn: "7311",
    minOrderQty: 1,
    inStock: true,
  },

  // 8. LINICH 3100 Auto Puller (Already exists, keeping reference)
  {
    id: "linich-3100-alt",
    name: "LINICH 3100 Auto Puller Professional",
    sku: "LIN-3100PRO",
    price: 85000,
    category: "special-tools",
    brand: "LINICH",
    image: "/images/products/linich-3100-auto-puller-professional.jpg",
    description:
      "Heavy-duty dent pulling system with manual and automatic triggering modes for high-precision body repair.",
    specs: {
      "Input Voltage": "220–230V AC",
      "Output Voltage": "7V AC",
      "Max Welding Output": "11 KVA",
      "Max Welding Current": "3000 A",
      "Protection Rating": "IP21",
      Weight: "29 kg",
      "Triggering Modes": "Manual & Automatic",
      Accessories: "Dent pulling hammer, Welding gun",
    },
    hsn: "8508",
    minOrderQty: 1,
    inStock: true,
  },

  // 9. AUTOMIG MW-250 3-Phase MIG Welding Machine (Already exists, adding alt)
  {
    id: "automig-250-pro",
    name: "AUTOMIG MW-250 Industrial MIG Welder",
    sku: "AUTO-250PRO",
    price: 125000,
    category: "welding",
    brand: "LINICH",
    image: "/images/products/automig-mw-250-industrial-mig-welder.jpg",
    description:
      "Robust three-phase MIG/MAG welding machine with optimized inductor for spatter-free continuous industrial use.",
    specs: {
      "Power Supply": "3-Phase, 440V",
      "Output Current": "60–250A",
      "Wire Diameter": "0.8 – 1.2 mm",
      Weight: "70 kg",
      Inductor: "Optimized for spatter reduction",
      "Energy Efficiency": "High",
      "Gas Cylinder": "Built-in stand",
    },
    hsn: "8515",
    minOrderQty: 1,
    inStock: true,
  },

  // 10. 4-Ton Hydraulic Two-Post Lift (Already exists, keeping)
  // Product already at ID 4

  // 11. LINICH SPOT LCR-70
  {
    id: "linich-spot-lcr70",
    name: "LINICH SPOT LCR-70 Spot Welder",
    sku: "LIN-LCR70",
    price: 145000,
    category: "welding",
    brand: "LINICH",
    image: "/images/products/linich-spot-lcr70-linich-welder.jpg",
    description:
      "Dual-purpose spot welder and dent puller with spring balancer and temperature-controlled air-cooled system.",
    specs: {
      "Input Voltage": "400V AC, 50Hz",
      "Max Output Current": "13,500 A",
      "Output Voltage": "7V (no-load), 3V (load)",
      "Protection Class": "IP22",
      Weight: "146 kg",
      Functionality: "Spot welding & dent pulling",
      Design: "Heavy-duty industrial",
      Cooling: "Temperature-controlled air-cooled",
    },
    hsn: "8515",
    minOrderQty: 1,
    inStock: true,
  },

  // 12. Air Compressor (Multiple Tank Capacities)
  {
    id: "air-comp-160l",
    name: "Air Compressor 160L Tank",
    sku: "AC-160L",
    price: 28000,
    category: "pneumatic",
    brand: "Generic Pro",
    image: "/images/products/air-compressor-160l-tank.jpg",
    description:
      "Industrial air compressor with 160L tank capacity. Single and twin cylinder configurations for workshop use.",
    specs: {
      "Tank Capacity": "160L",
      Cylinder: "Single",
      "Stable RPM": "Yes",
      Applications: "Heavy workshop usage, Pneumatic tools, Paint booths",
      "Build Quality": "Industrial grade",
    },
    hsn: "8414",
    minOrderQty: 1,
    inStock: true,
  },

  // 13. Transmission Jack – 0.5 / 1 Ton
  {
    id: "trans-jack-500kg",
    name: "Transmission Jack 500kg",
    sku: "TJ-500K",
    price: 10000,
    category: "transmission",
    brand: "Generic Pro",
    image: "/images/products/transmission-jack-500kg.jpg",
    description:
      "Heavy-duty hydraulic transmission jack for safe and controlled transmission removal and installation.",
    specs: {
      Capacity: "500 kg (0.5 Ton)",
      "Hydraulic Lifting": "Heavy-duty",
      "Wide Base": "Stability",
      "Height Adjustment": "Smooth",
      Construction: "Workshop-grade",
      Features: "Adjustable saddle, Safety valve",
    },
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // 14. Engine Crane – 2 Ton / 3 Ton
  {
    id: "engine-crane-2t",
    name: "Engine Crane 2 Ton",
    sku: "EC-2T",
    price: 22000,
    category: "lifting",
    brand: "Generic Pro",
    image: "/images/products/engine-crane-2ton.jpg",
    description:
      "Engine crane built for lifting and positioning engines safely during vehicle maintenance and overhaul operations.",
    specs: {
      "Lifting Capacity": "2 Ton",
      Frame: "Reinforced steel",
      Control: "Smooth hydraulic",
      Mobility: "Easy with caster wheels",
      Applications: "Engine handling during maintenance, Overhaul operations",
    },
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // 15. Hydraulic Press – 20 Ton / 30 Ton
  {
    id: "hydr-press-50t",
    name: "Hydraulic Press 50 Ton",
    sku: "HP-50T",
    price: 68000,
    category: "special-tools",
    brand: "Generic Pro",
    image: "/images/products/hydraulic-press-50ton.jpg",
    description:
      "Heavy-duty hydraulic press for pressing, bending, and straightening metal components in automotive workshops.",
    specs: {
      Capacity: "50 Ton",
      "Pressure Output": "High",
      "Working Range": "Adjustable",
      Structure: "Strong welded steel",
      "Hydraulic Performance": "Reliable",
      Applications: "Metal pressing, Bending, Straightening",
    },
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // 16. Vacuum Cleaner – 30L / 80L
  {
    id: "vacuum-80l",
    name: "Vacuum Cleaner 80L Industrial",
    sku: "VC-80L",
    price: 32000,
    category: "pneumatic",
    brand: "Generic Pro",
    image: "/images/products/vacuum-cleaner-80l.jpg",
    description:
      "Industrial dry and wet vacuum cleaner designed for cleaning dust, debris, and liquid waste in workshops.",
    specs: {
      Capacity: "80L",
      Functionality: "Dry & wet",
      "Suction Power": "High",
      "Cooling System": "Recyclable",
      Construction: "Durable",
      Applications: "Workshop cleaning, Paint areas",
    },
    hsn: "8408",
    minOrderQty: 1,
    inStock: true,
  },

  // 17. Infra-Red Paint Curing Lamp
  {
    id: "ir-cure-lamp",
    name: "Infra-Red Paint Curing Lamp",
    sku: "IRCL-PRO",
    price: 45000,
    category: "painting",
    brand: "Generic Pro",
    image: "/images/products/infrared-cure-lamp.jpg",
    description:
      "Infrared curing system that accelerates paint drying with adjustable temperature and automatic overload protection.",
    specs: {
      "Temperature Range": "40°C–80°C",
      "Timer Control": "Electronic",
      "Overload Protection": "Automatic",
      "Lamp Angle": "Adjustable",
      Height: "Adjustable",
      Lamps: "Energy-efficient halogen",
      Applications: "Automotive paint booths, Paint curing",
    },
    hsn: "8516",
    minOrderQty: 1,
    inStock: true,
  },

  // 18. Chain Lever Block – 1.5 Ton / 3 Ton
  {
    id: "chain-lever-3t",
    name: "Chain Lever Block 3 Ton",
    sku: "CLB-3T",
    price: 8500,
    category: "lifting",
    brand: "Generic Pro",
    image: "/images/products/chain-lever-block-3ton.jpg",
    description:
      "Chain lever blocks designed for controlled lifting and pulling operations in workshops and industrial environments.",
    specs: {
      Capacity: "3 Ton",
      "Load Chain": "High-strength",
      Design: "Compact and portable",
      Operation: "Smooth mechanical",
      Application: "Heavy-duty lifting, Pulling operations",
    },
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // 19. Wheel Dolly
  {
    id: "wheel-dolly",
    name: "Wheel Dolly Set",
    sku: "WD-SET",
    price: 4200,
    category: "lifting",
    brand: "Generic Pro",
    image: "/images/products/wheel-dolly.jpg",
    description: "Wheel dollies allow easy maneuvering of vehicles inside workshops without engine operation.",
    specs: {
      Construction: "Heavy-duty steel",
      Wheels: "Smooth rolling",
      Positioning: "Easy vehicle movement",
      Features: "Professional grade",
    },
    hsn: "8708",
    minOrderQty: 1,
    inStock: true,
  },

  // 20. 5-Ton Floor Jack
  {
    id: "floor-jack-5t-pro",
    name: "5-Ton Floor Jack Professional",
    sku: "FJ-5TP",
    price: 9200,
    category: "lifting",
    brand: "Generic Pro",
    image: "/images/products/floor-jack-5ton.jpg",
    description: "Robust floor jack designed for lifting heavy vehicles safely and efficiently.",
    specs: {
      "Lifting Capacity": "5 Ton",
      "Base Width": "Stable wide",
      Operation: "Smooth hydraulic",
      Features: "Professional grade, Maneuverable design",
    },
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // 21. Car Creeper
  {
    id: "car-creeper-pro",
    name: "Car Creeper Professional",
    sku: "CC-PRO",
    price: 3500,
    category: "special-tools",
    brand: "Generic Pro",
    image: "/images/products/car-creeper.jpg",
    description:
      "Car creeper provides comfortable under-vehicle access for technicians during inspections and repairs.",
    specs: {
      Design: "Low-profile",
      Casters: "Easy rolling",
      Surface: "Durable padded",
      Features: "Professional grade",
    },
    hsn: "94019090",
    minOrderQty: 1,
    inStock: true,
  },

  // 22. Engine Support Beam
  {
    id: "engine-support-beam",
    name: "Engine Support Beam",
    sku: "ESB-PRO",
    price: 6500,
    category: "lifting",
    brand: "Generic Pro",
    image: "/images/products/engine-support-beam.jpg",
    description: "Used to support engines safely during transmission or subframe removal operations.",
    specs: {
      "Support Arms": "Adjustable",
      Construction: "Strong steel",
      "Mounting System": "Secure",
      Applications: "Engine support during service",
    },
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // 23. Axle Stand – 3 Ton
  {
    id: "axle-stand-3t",
    name: "Axle Stand 3 Ton",
    sku: "AS-3T",
    price: 2800,
    category: "lifting",
    brand: "Generic Pro",
    image: "/images/products/axle-stand-3ton.jpg",
    description: "Axle stands provide secure support for vehicles during maintenance work.",
    specs: {
      "Steel Body": "Heavy-duty",
      "Height Adjustment": "Locking mechanism",
      "Base Design": "Stable",
      Features: "Safety-certified",
    },
    hsn: "8425",
    minOrderQty: 2,
    inStock: true,
  },

  // 24. 10-Ton Body Frame Straightener
  {
    id: "body-frame-10t",
    name: "10-Ton Body Frame Straightener",
    sku: "BFS-10T",
    price: 185000,
    category: "special-tools",
    brand: "Generic Pro",
    image: "/images/products/body-frame-straightener-10ton.jpg",
    description:
      "Designed for heavy collision repair, this system restores vehicle frames with controlled hydraulic force.",
    specs: {
      "Hydraulic Capacity": "10 Ton",
      "Pulling Tower": "Adjustable",
      Application: "Professional collision repair",
      Features: "Precision control, Heavy-duty rated",
    },
    hsn: "8425",
    minOrderQty: 1,
    inStock: false,
  },

  // 25. 10-Ton Body Puller Kit
  {
    id: "body-puller-10t",
    name: "10-Ton Body Puller Kit",
    sku: "BPK-10T",
    price: 48000,
    category: "special-tools",
    brand: "Generic Pro",
    image: "/images/products/body-puller-kit-10ton.jpg",
    description: "Complete kit for body pulling operations, suitable for structural and cosmetic repairs.",
    specs: {
      Capacity: "10 Ton",
      "Kit Contents": "Complete set",
      Applications: "Dent and frame repair, Structural work",
      Features: "Professional grade",
    },
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // 26. Hydraulic Coil Spring Compressor
  {
    id: "spring-compressor",
    name: "Hydraulic Coil Spring Compressor",
    sku: "HCSC-PRO",
    price: 7800,
    category: "special-tools",
    brand: "Generic Pro",
    image: "/images/products/spring-compressor.jpg",
    description: "Safely compresses suspension springs during repair and replacement operations.",
    specs: {
      "Spring Locking": "Secure",
      "Hydraulic Control": "Heavy-duty",
      Construction: "Workshop-grade",
      Safety: "Professional rated",
    },
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // 27. Engine Stand
  {
    id: "engine-stand-pro",
    name: "Engine Stand Professional",
    sku: "ES-PRO",
    price: 9500,
    category: "lifting",
    brand: "Generic Pro",
    image: "/images/products/engine-stand.jpg",
    description: "Allows safe mounting and rotation of engines during overhaul and rebuilding operations.",
    specs: {
      Mounting: "Safe and secure",
      Rotation: "360° capability",
      Applications: "Engine rebuilding, Overhaul work",
      Features: "Professional grade",
    },
    hsn: "8425",
    minOrderQty: 1,
    inStock: true,
  },

  // 28. Bosch GPO 12 CE Polisher
  {
    id: "bosch-gpo12",
    name: "Bosch GPO 12 CE Polisher",
    sku: "BOSCH-GPO12",
    price: 14000,
    category: "power-tools",
    brand: "Bosch",
    image: "/images/products/bosch-gpo12-polisher.jpg",
    description:
      "Professional polishing machine with variable speed control and high torque motor for superior finishing.",
    specs: {
      "Variable Speed": "Yes",
      "Torque Motor": "High",
      Performance: "Professional polishing",
      Applications: "Surface finishing, Detailing",
    },
    hsn: "8463",
    minOrderQty: 1,
    inStock: true,
  },

  // 29. Bosch Rotary Drill GBS 600
  {
    id: "bosch-gbs600",
    name: "Bosch Rotary Drill GBS 600",
    sku: "BOSCH-GBS600",
    price: 11500,
    category: "power-tools",
    brand: "Bosch",
    image: "/images/products/bosch-gbs600-drill.jpg",
    description: "Professional-grade rotary drill for heavy-duty drilling operations.",
    specs: {
      Power: "Professional grade",
      "Chuck Type": "Keyed",
      Performance: "High torque",
      Applications: "Heavy-duty drilling",
    },
    hsn: "8463",
    minOrderQty: 1,
    inStock: true,
  },

  // 30. Bosch Heat Gun GHG 180
  {
    id: "bosch-ghg180",
    name: "Bosch Heat Gun GHG 180",
    sku: "BOSCH-GHG180",
    price: 5800,
    category: "power-tools",
    brand: "Bosch",
    image: "/images/products/bosch-ghg180-heat-gun.jpg",
    description: "Professional heat gun with variable temperature for paint stripping and component heating.",
    specs: {
      "Variable Temperature": "Yes",
      Power: "Professional grade",
      Applications: "Paint stripping, Component heating",
    },
    hsn: "8463",
    minOrderQty: 1,
    inStock: true,
  },

  // 31. Bosch Angle Grinder GWS 800
  {
    id: "bosch-gws800-alt",
    name: "Bosch Angle Grinder GWS 800 Professional",
    sku: "BOSCH-GWS800ALT",
    price: 4200,
    category: "power-tools",
    brand: "Bosch",
    image: "/images/products/bosch-gws800-grinder.jpg",
    description:
      "Professional 800W angle grinder with safety features and reliable performance for cutting and grinding.",
    specs: {
      Power: "800W",
      "Disc Size": "100mm",
      Speed: "11000 RPM",
      Applications: "Metal cutting, Grinding",
    },
    hsn: "8463",
    minOrderQty: 1,
    inStock: true,
  },

  // 32. Bosch High Pressure Washer (GHP Series)
  {
    id: "bosch-ghp",
    name: "Bosch High Pressure Washer GHP Series",
    sku: "BOSCH-GHP",
    price: 18500,
    category: "spray-guns",
    brand: "Bosch",
    image: "/images/products/bosch-pressure-washer.jpg",
    description: "Professional-grade Bosch power tools designed for durability, efficiency, and workshop reliability.",
    specs: {
      Pressure: "Professional grade",
      Power: "Industrial rated",
      Durability: "Long-lasting",
      Applications: "Vehicle and equipment cleaning",
    },
    hsn: "8463",
    minOrderQty: 1,
    inStock: true,
  },

  // 33. 3M Clean Sanding System
  {
    id: "3m-sanding",
    name: "3M Clean Sanding System",
    sku: "3M-SAND",
    price: 12000,
    category: "power-tools",
    brand: "3M",
    image: "/images/products/3m-sanding-system.jpg",
    description: "Professional dust-free sanding system that improves working environment and productivity.",
    specs: {
      "Dust-free": "Yes",
      Environment: "Improved air quality",
      Productivity: "Increased",
      Applications: "Surface preparation",
    },
    hsn: "8463",
    minOrderQty: 1,
    inStock: true,
  },

  // 34. 3M Performance Spray Gun (Already exists, updating)
  {
    id: "3m-spray-pro",
    name: "3M Performance Spray Gun Professional",
    sku: "3M-SPRAY",
    price: 13500,
    category: "spray-guns",
    brand: "3M",
    image: "/images/products/3m-performance-spray.jpg",
    description:
      "Lightweight spray gun with high transfer efficiency for professional paint finish in automotive applications.",
    specs: {
      "Lightweight Design": "Yes",
      "Transfer Efficiency": "High",
      "Professional Finish": "Superior",
      Applications: "Automotive painting",
    },
    hsn: "7311",
    minOrderQty: 1,
    inStock: true,
  },

  // 35. Menzerna Polishing Compounds
  {
    id: "menzerna-polish",
    name: "Menzerna Polishing Compounds Set",
    sku: "MENZERNA-POLISH",
    price: 4500,
    category: "painting",
    brand: "Menzerna",
    image: "/images/products/menzerna-compounds.jpg",
    description: "Professional polishing compounds with high-gloss finish and multiple cutting & polishing stages.",
    specs: {
      "High-gloss Finish": "Yes",
      "Cutting Stages": "Multiple",
      "Polishing Stages": "Multiple",
      Applications: "Professional detailing",
    },
    hsn: "3405",
    minOrderQty: 1,
    inStock: true,
  },

  // 36. MIRKA Sanding & Polishing Systems
  {
    id: "mirka-systems",
    name: "MIRKA Sanding & Polishing Systems",
    sku: "MIRKA-SYSTEM",
    price: 22000,
    category: "power-tools",
    brand: "MIRKA",
    image: "/images/products/mirka-systems.jpg",
    description: "Dust-free sanding technology with ergonomic power tools approved for automotive refinishing.",
    specs: {
      "Dust-free": "Yes",
      Ergonomic: "Yes",
      "Industry Approved": "Yes",
      Applications: "Automotive refinishing",
    },
    hsn: "8463",
    minOrderQty: 1,
    inStock: true,
  },

  // 37. MaxShine Detailing Equipment
  {
    id: "maxshine-detail",
    name: "MaxShine Detailing Equipment Kit",
    sku: "MAXSHINE-KIT",
    price: 8500,
    category: "special-tools",
    brand: "MaxShine",
    image: "/images/products/maxshine-detail-kit.jpg",
    description: "Professional detailing accessories and workshop-ready solutions for automotive finishing.",
    specs: {
      Accessories: "Professional grade",
      "Workshop Ready": "Yes",
      Applications: "Auto detailing",
    },
    hsn: "3405",
    minOrderQty: 1,
    inStock: true,
  },

  // 38. PCL-SUMO Nitrogen Generator Cum Inflator (Already exists, updating)
  {
    id: "pcl-sumo-pro",
    name: "PCL-SUMO Nitrogen Generator Cum Inflator",
    sku: "PCL-SUMO",
    price: 95000,
    category: "pneumatic",
    brand: "PCL",
    image: "/images/products/pcl-sumo-nitrogen.jpg",
    description:
      "Professional PSA nitrogen generation system with simultaneous 4-tyre inflation and air/nitrogen selector.",
    specs: {
      Technology: "PSA nitrogen generation",
      "Tyre Inflation": "Simultaneous 4 tires",
      Selector: "Air / Nitrogen",
      Purity: "Consistent high N₂",
      Applications: "Tyre inflation systems",
    },
    hsn: "8414",
    minOrderQty: 1,
    inStock: true,
  },

  // 39. ACCURA Compact D60 Digital Inflator
  {
    id: "accura-d60",
    name: "ACCURA Compact D60 Digital Inflator",
    sku: "ACCURA-D60",
    price: 8500,
    category: "pneumatic",
    brand: "ACCURA",
    image: "/images/products/accura-d60-inflator.jpg",
    description: "Compact digital inflator with pressure accuracy for precise tyre inflation and diagnostics.",
    specs: {
      Display: "Digital pressure accuracy",
      Design: "Compact & durable",
      Features: "Professional grade",
      Applications: "Tyre inflation",
    },
    hsn: "8414",
    minOrderQty: 1,
    inStock: true,
  },

  // 40. ACCURA QUBE Digital Inflator
  {
    id: "accura-qube",
    name: "ACCURA QUBE Digital Inflator",
    sku: "ACCURA-QUBE",
    price: 12000,
    category: "pneumatic",
    brand: "ACCURA",
    image: "/images/products/accura-qube-inflator.jpg",
    description: "Advanced digital inflator with touchscreen operation for modern tyre inflation requirements.",
    specs: {
      Display: "Touchscreen digital",
      Accuracy: "High precision",
      Operation: "User-friendly",
      Design: "Compact & durable",
    },
    hsn: "8414",
    minOrderQty: 1,
    inStock: true,
  },

  // 41. Measuring Tools & Accessories
  {
    id: "measuring-tools-kit",
    name: "Measuring Tools & Accessories Kit",
    sku: "MEAS-KIT",
    price: 18000,
    category: "measurement",
    brand: "Generic Pro",
    image: "/images/products/measuring-tools-kit.jpg",
    description: "Complete precision tools kit including digital torque wrench, micrometer, vernier caliper, and more.",
    specs: {
      Includes: "Digital torque wrench, Micrometer, Vernier caliper, Oil pressure tester, Bearing pullers, Socket sets",
      Applications: "Diagnostics, Measurement, Workshop servicing",
      "Essential Tools": "Complete set",
    },
    hsn: "9031",
    minOrderQty: 1,
    inStock: true,
  },
]

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.category === categoryId)
}

export function getProductsByBrand(brand: string): Product[] {
  return products.filter((p) => p.brand === brand)
}

export function getTopProducts(count = 10): Product[] {
  return products.slice(0, count)
}

export function getOfferProducts(): Product[] {
  return products.filter((p) => p.isOffer)
}

export function searchProducts(query: string): Product[] {
  const lowercaseQuery = query.toLowerCase()
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lowercaseQuery) ||
      p.description.toLowerCase().includes(lowercaseQuery) ||
      p.brand.toLowerCase().includes(lowercaseQuery) ||
      p.sku.toLowerCase().includes(lowercaseQuery),
  )
}
